/**
 * 스프라이트 에셋 인덱스 — **자동 생성 파일. 직접 수정하지 마세요.**
 *   생성: python3 tools/slice.py
 *   원본: assets/lending-image/, assets/new-image/ (마젠타 경계 시트)
 */

export const SCROLL_SPRITES = {
  'guarantee': require('../../assets/sprites/scroll/guarantee.png'),
  'guard_destroy100': require('../../assets/sprites/scroll/guard_destroy100.png'),
  'guard_destroy50': require('../../assets/sprites/scroll/guard_destroy50.png'),
  'guard_down': require('../../assets/sprites/scroll/guard_down.png'),
  'succ_high': require('../../assets/sprites/scroll/succ_high.png'),
  'succ_low': require('../../assets/sprites/scroll/succ_low.png'),
  'succ_mid': require('../../assets/sprites/scroll/succ_mid.png'),
} as const;

export const WEAPON_SPRITES = {
  'axe': require('../../assets/sprites/weapon/axe.png'),
  'blade': require('../../assets/sprites/weapon/blade.png'),
  'bow': require('../../assets/sprites/weapon/bow.png'),
  'crossbow': require('../../assets/sprites/weapon/crossbow.png'),
  'fan': require('../../assets/sprites/weapon/fan.png'),
  'hammer': require('../../assets/sprites/weapon/hammer.png'),
  'mace': require('../../assets/sprites/weapon/mace.png'),
  'rod': require('../../assets/sprites/weapon/rod.png'),
  'spear': require('../../assets/sprites/weapon/spear.png'),
  'staff': require('../../assets/sprites/weapon/staff.png'),
  'sword': require('../../assets/sprites/weapon/sword.png'),
} as const;

export const ATTEND_SPRITES = {
  'cal_empty': require('../../assets/sprites/attend/cal_empty.png'),
  'cal_missed': require('../../assets/sprites/attend/cal_missed.png'),
  'cal_stamped': require('../../assets/sprites/attend/cal_stamped.png'),
  'cal_today': require('../../assets/sprites/attend/cal_today.png'),
  'stamp_check': require('../../assets/sprites/attend/stamp_check.png'),
  'stamp_flame': require('../../assets/sprites/attend/stamp_flame.png'),
  'stamp_moon': require('../../assets/sprites/attend/stamp_moon.png'),
  'stamp_sun': require('../../assets/sprites/attend/stamp_sun.png'),
} as const;

export const GEAR_SPRITES = {
  'belt': require('../../assets/sprites/gear/belt.png'),
  'boot': require('../../assets/sprites/gear/boot.png'),
  'chest': require('../../assets/sprites/gear/chest.png'),
  'ear': require('../../assets/sprites/gear/ear.png'),
  'glove': require('../../assets/sprites/gear/glove.png'),
  'greaves': require('../../assets/sprites/gear/greaves.png'),
  'helm': require('../../assets/sprites/gear/helm.png'),
  'neck': require('../../assets/sprites/gear/neck.png'),
  'ring': require('../../assets/sprites/gear/ring.png'),
} as const;

export const CARD_SPRITES = {
  'm01_1': require('../../assets/sprites/card/m01_1.png'),
  'm01_2': require('../../assets/sprites/card/m01_2.png'),
  'm01_3': require('../../assets/sprites/card/m01_3.png'),
  'm01_4': require('../../assets/sprites/card/m01_4.png'),
  'm02_1': require('../../assets/sprites/card/m02_1.png'),
  'm02_2': require('../../assets/sprites/card/m02_2.png'),
  'm02_3': require('../../assets/sprites/card/m02_3.png'),
  'm02_4': require('../../assets/sprites/card/m02_4.png'),
  'm03_1': require('../../assets/sprites/card/m03_1.png'),
  'm03_2': require('../../assets/sprites/card/m03_2.png'),
  'm03_3': require('../../assets/sprites/card/m03_3.png'),
  'm03_4': require('../../assets/sprites/card/m03_4.png'),
  'm04_1': require('../../assets/sprites/card/m04_1.png'),
  'm04_2': require('../../assets/sprites/card/m04_2.png'),
  'm04_3': require('../../assets/sprites/card/m04_3.png'),
  'm04_4': require('../../assets/sprites/card/m04_4.png'),
  'm05_1': require('../../assets/sprites/card/m05_1.png'),
  'm05_2': require('../../assets/sprites/card/m05_2.png'),
  'm05_3': require('../../assets/sprites/card/m05_3.png'),
  'm05_4': require('../../assets/sprites/card/m05_4.png'),
  'm06_1': require('../../assets/sprites/card/m06_1.png'),
  'm06_2': require('../../assets/sprites/card/m06_2.png'),
  'm06_3': require('../../assets/sprites/card/m06_3.png'),
  'm06_4': require('../../assets/sprites/card/m06_4.png'),
  'm07_1': require('../../assets/sprites/card/m07_1.png'),
  'm07_2': require('../../assets/sprites/card/m07_2.png'),
  'm07_3': require('../../assets/sprites/card/m07_3.png'),
  'm07_4': require('../../assets/sprites/card/m07_4.png'),
  'm08_1': require('../../assets/sprites/card/m08_1.png'),
  'm08_2': require('../../assets/sprites/card/m08_2.png'),
  'm08_3': require('../../assets/sprites/card/m08_3.png'),
  'm08_4': require('../../assets/sprites/card/m08_4.png'),
  'm09_1': require('../../assets/sprites/card/m09_1.png'),
  'm09_2': require('../../assets/sprites/card/m09_2.png'),
  'm09_3': require('../../assets/sprites/card/m09_3.png'),
  'm09_4': require('../../assets/sprites/card/m09_4.png'),
  'm10_1': require('../../assets/sprites/card/m10_1.png'),
  'm10_2': require('../../assets/sprites/card/m10_2.png'),
  'm10_3': require('../../assets/sprites/card/m10_3.png'),
  'm10_4': require('../../assets/sprites/card/m10_4.png'),
} as const;

export const TITLE_SPRITES = {
  'abyss_diver': require('../../assets/sprites/title/abyss_diver.png'),
  'alchemist': require('../../assets/sprites/title/alchemist.png'),
  'all_in': require('../../assets/sprites/title/all_in.png'),
  'angler': require('../../assets/sprites/title/angler.png'),
  'artisan_path': require('../../assets/sprites/title/artisan_path.png'),
  'bankrupt_king': require('../../assets/sprites/title/bankrupt_king.png'),
  'bernstein_slayer': require('../../assets/sprites/title/bernstein_slayer.png'),
  'coin_believer': require('../../assets/sprites/title/coin_believer.png'),
  'curator': require('../../assets/sprites/title/curator.png'),
  'curse13': require('../../assets/sprites/title/curse13.png'),
  'day_trader': require('../../assets/sprites/title/day_trader.png'),
  'defaulter': require('../../assets/sprites/title/defaulter.png'),
  'first_artisan': require('../../assets/sprites/title/first_artisan.png'),
  'first_hundred': require('../../assets/sprites/title/first_hundred.png'),
  'first_player': require('../../assets/sprites/title/first_player.png'),
  'first_sss': require('../../assets/sprites/title/first_sss.png'),
  'first_summit': require('../../assets/sprites/title/first_summit.png'),
  'first_thousand': require('../../assets/sprites/title/first_thousand.png'),
  'gather_king': require('../../assets/sprites/title/gather_king.png'),
  'gladiator': require('../../assets/sprites/title/gladiator.png'),
  'guild_founder': require('../../assets/sprites/title/guild_founder.png'),
  'gwang38': require('../../assets/sprites/title/gwang38.png'),
  'hunter': require('../../assets/sprites/title/hunter.png'),
  'iron_wallet': require('../../assets/sprites/title/iron_wallet.png'),
  'lucky_hand': require('../../assets/sprites/title/lucky_hand.png'),
  'night_owl': require('../../assets/sprites/title/night_owl.png'),
  'polymath': require('../../assets/sprites/title/polymath.png'),
  'rune_master': require('../../assets/sprites/title/rune_master.png'),
  'rune_smith': require('../../assets/sprites/title/rune_smith.png'),
  'set_keeper': require('../../assets/sprites/title/set_keeper.png'),
  'tower_conqueror': require('../../assets/sprites/title/tower_conqueror.png'),
  'veteran': require('../../assets/sprites/title/veteran.png'),
  'weapon_collector': require('../../assets/sprites/title/weapon_collector.png'),
} as const;

export const BUBBLE_SPRITES = {
  'conversation': require('../../assets/sprites/bubble/conversation.png'),
  'empty': require('../../assets/sprites/bubble/empty.png'),
  'message': require('../../assets/sprites/bubble/message.png'),
  'typing': require('../../assets/sprites/bubble/typing.png'),
} as const;

export const JACKPOT_SPRITES = {
  '01': require('../../assets/sprites/jackpot/01.png'),
  '02': require('../../assets/sprites/jackpot/02.png'),
  '03': require('../../assets/sprites/jackpot/03.png'),
  '04': require('../../assets/sprites/jackpot/04.png'),
  '05': require('../../assets/sprites/jackpot/05.png'),
} as const;

export const CREATURE_SPRITES = {
  'bat': require('../../assets/sprites/creature/bat.png'),
  'boar': require('../../assets/sprites/creature/boar.png'),
  'golem': require('../../assets/sprites/creature/golem.png'),
  'mantis': require('../../assets/sprites/creature/mantis.png'),
  'ogre': require('../../assets/sprites/creature/ogre.png'),
  'skeleton': require('../../assets/sprites/creature/skeleton.png'),
  'slime': require('../../assets/sprites/creature/slime.png'),
  'tentacle': require('../../assets/sprites/creature/tentacle.png'),
  'toad': require('../../assets/sprites/creature/toad.png'),
  'wolf': require('../../assets/sprites/creature/wolf.png'),
} as const;

export const CR_SLIME_SPRITES = {
  'attack': require('../../assets/sprites/cr_slime/attack.png'),
  'down': require('../../assets/sprites/cr_slime/down.png'),
  'idle': require('../../assets/sprites/cr_slime/idle.png'),
  'windup': require('../../assets/sprites/cr_slime/windup.png'),
} as const;

export const CR_WOLF_SPRITES = {
  'attack': require('../../assets/sprites/cr_wolf/attack.png'),
  'down': require('../../assets/sprites/cr_wolf/down.png'),
  'idle': require('../../assets/sprites/cr_wolf/idle.png'),
  'windup': require('../../assets/sprites/cr_wolf/windup.png'),
} as const;

export const CR_GOLEM_SPRITES = {
  'attack': require('../../assets/sprites/cr_golem/attack.png'),
  'down': require('../../assets/sprites/cr_golem/down.png'),
  'idle': require('../../assets/sprites/cr_golem/idle.png'),
  'windup': require('../../assets/sprites/cr_golem/windup.png'),
} as const;

export const CR_BAT_SPRITES = {
  'attack': require('../../assets/sprites/cr_bat/attack.png'),
  'down': require('../../assets/sprites/cr_bat/down.png'),
  'idle': require('../../assets/sprites/cr_bat/idle.png'),
  'windup': require('../../assets/sprites/cr_bat/windup.png'),
} as const;

export const CR_BOAR_SPRITES = {
  'attack': require('../../assets/sprites/cr_boar/attack.png'),
  'down': require('../../assets/sprites/cr_boar/down.png'),
  'idle': require('../../assets/sprites/cr_boar/idle.png'),
  'windup': require('../../assets/sprites/cr_boar/windup.png'),
} as const;

export const CR_SKELETON_SPRITES = {
  'attack': require('../../assets/sprites/cr_skeleton/attack.png'),
  'down': require('../../assets/sprites/cr_skeleton/down.png'),
  'idle': require('../../assets/sprites/cr_skeleton/idle.png'),
  'windup': require('../../assets/sprites/cr_skeleton/windup.png'),
} as const;

export const CR_TOAD_SPRITES = {
  'attack': require('../../assets/sprites/cr_toad/attack.png'),
  'down': require('../../assets/sprites/cr_toad/down.png'),
  'idle': require('../../assets/sprites/cr_toad/idle.png'),
  'windup': require('../../assets/sprites/cr_toad/windup.png'),
} as const;

export const CR_MANTIS_SPRITES = {
  'attack': require('../../assets/sprites/cr_mantis/attack.png'),
  'down': require('../../assets/sprites/cr_mantis/down.png'),
  'idle': require('../../assets/sprites/cr_mantis/idle.png'),
  'windup': require('../../assets/sprites/cr_mantis/windup.png'),
} as const;

export const CR_OGRE_SPRITES = {
  'attack': require('../../assets/sprites/cr_ogre/attack.png'),
  'down': require('../../assets/sprites/cr_ogre/down.png'),
  'idle': require('../../assets/sprites/cr_ogre/idle.png'),
  'windup': require('../../assets/sprites/cr_ogre/windup.png'),
} as const;

export const CR_TENTACLE_SPRITES = {
  'attack': require('../../assets/sprites/cr_tentacle/attack.png'),
  'down': require('../../assets/sprites/cr_tentacle/down.png'),
  'idle': require('../../assets/sprites/cr_tentacle/idle.png'),
  'windup': require('../../assets/sprites/cr_tentacle/windup.png'),
} as const;

export const BG_CHAPTER_SPRITES = {
  '01': require('../../assets/sprites/bg_chapter/01.png'),
  '02': require('../../assets/sprites/bg_chapter/02.png'),
} as const;

export const BG_PLACE_SPRITES = {
  'abyss': require('../../assets/sprites/bg_place/abyss.png'),
  'alchemist': require('../../assets/sprites/bg_place/alchemist.png'),
  'arena': require('../../assets/sprites/bg_place/arena.png'),
  'artisan': require('../../assets/sprites/bg_place/artisan.png'),
  'beastwood': require('../../assets/sprites/bg_place/beastwood.png'),
  'fish': require('../../assets/sprites/bg_place/fish.png'),
  'gamble': require('../../assets/sprites/bg_place/gamble.png'),
  'gather': require('../../assets/sprites/bg_place/gather.png'),
  'hill_house': require('../../assets/sprites/bg_place/hill_house.png'),
  'house': require('../../assets/sprites/bg_place/house.png'),
  'hunt': require('../../assets/sprites/bg_place/hunt.png'),
  'mine': require('../../assets/sprites/bg_place/mine.png'),
  'office': require('../../assets/sprites/bg_place/office.png'),
  'shop': require('../../assets/sprites/bg_place/shop.png'),
  'tavern': require('../../assets/sprites/bg_place/tavern.png'),
  'tower': require('../../assets/sprites/bg_place/tower.png'),
} as const;

export const JOB_SPRITES = {
  'bellows': require('../../assets/sprites/job/bellows.png'),
  'broom': require('../../assets/sprites/job/broom.png'),
  'bucket': require('../../assets/sprites/job/bucket.png'),
  'cart': require('../../assets/sprites/job/cart.png'),
  'flyer': require('../../assets/sprites/job/flyer.png'),
  'hay': require('../../assets/sprites/job/hay.png'),
  'ice': require('../../assets/sprites/job/ice.png'),
  'shovel': require('../../assets/sprites/job/shovel.png'),
} as const;

export const AVATAR_SPRITES = {
  'archer': require('../../assets/sprites/avatar/archer.png'),
  'baron': require('../../assets/sprites/avatar/baron.png'),
  'bunnyaxe': require('../../assets/sprites/avatar/bunnyaxe.png'),
  'bunnyblade': require('../../assets/sprites/avatar/bunnyblade.png'),
  'deserter': require('../../assets/sprites/avatar/deserter.png'),
  'duelist': require('../../assets/sprites/avatar/duelist.png'),
  'elfarcher': require('../../assets/sprites/avatar/elfarcher.png'),
  'knight': require('../../assets/sprites/avatar/knight.png'),
  'knightgirl': require('../../assets/sprites/avatar/knightgirl.png'),
  'maidhammer': require('../../assets/sprites/avatar/maidhammer.png'),
  'mercenary': require('../../assets/sprites/avatar/mercenary.png'),
  'merchant': require('../../assets/sprites/avatar/merchant.png'),
  'miner': require('../../assets/sprites/avatar/miner.png'),
  'nun': require('../../assets/sprites/avatar/nun.png'),
  'regular': require('../../assets/sprites/avatar/regular.png'),
  'robber': require('../../assets/sprites/avatar/robber.png'),
  'spearman': require('../../assets/sprites/avatar/spearman.png'),
  'swordsman': require('../../assets/sprites/avatar/swordsman.png'),
  'witchgirl': require('../../assets/sprites/avatar/witchgirl.png'),
} as const;

export const SINGLE_ICON_SPRITES = {
  '01': require('../../assets/sprites/single_icon/01.png'),
} as const;

export const SINGLE_ICON_ALT_SPRITES = {
  '01': require('../../assets/sprites/single_icon_alt/01.png'),
} as const;

export const SINGLE_SPLASH_SPRITES = {
  '01': require('../../assets/sprites/single_splash/01.png'),
} as const;

export const PL_ATTACK_SPRITES = {
  'cast_1': require('../../assets/sprites/pl_attack/cast_1.png'),
  'cast_2': require('../../assets/sprites/pl_attack/cast_2.png'),
  'cast_3': require('../../assets/sprites/pl_attack/cast_3.png'),
  'shoot_1': require('../../assets/sprites/pl_attack/shoot_1.png'),
  'shoot_2': require('../../assets/sprites/pl_attack/shoot_2.png'),
  'shoot_3': require('../../assets/sprites/pl_attack/shoot_3.png'),
  'slash_1': require('../../assets/sprites/pl_attack/slash_1.png'),
  'slash_2': require('../../assets/sprites/pl_attack/slash_2.png'),
  'slash_3': require('../../assets/sprites/pl_attack/slash_3.png'),
  'smash_1': require('../../assets/sprites/pl_attack/smash_1.png'),
  'smash_2': require('../../assets/sprites/pl_attack/smash_2.png'),
  'smash_3': require('../../assets/sprites/pl_attack/smash_3.png'),
  'thrust_1': require('../../assets/sprites/pl_attack/thrust_1.png'),
  'thrust_2': require('../../assets/sprites/pl_attack/thrust_2.png'),
  'thrust_3': require('../../assets/sprites/pl_attack/thrust_3.png'),
} as const;

export const CARD_BACK_SPRITES = {
  'checker': require('../../assets/sprites/card_back/checker.png'),
  'diamond': require('../../assets/sprites/card_back/diamond.png'),
  'frames': require('../../assets/sprites/card_back/frames.png'),
  'frames2': require('../../assets/sprites/card_back/frames2.png'),
  'lattice': require('../../assets/sprites/card_back/lattice.png'),
} as const;

export const COIN_SPRITES = {
  'copper': require('../../assets/sprites/coin/copper.png'),
  'gold': require('../../assets/sprites/coin/gold.png'),
  'silver': require('../../assets/sprites/coin/silver.png'),
} as const;

export const CROWD_SPRITES = {
  'cheer': require('../../assets/sprites/crowd/cheer.png'),
  'jeer': require('../../assets/sprites/crowd/jeer.png'),
  'neutral': require('../../assets/sprites/crowd/neutral.png'),
  'react_cheer': require('../../assets/sprites/crowd/react_cheer.png'),
  'react_jeer': require('../../assets/sprites/crowd/react_jeer.png'),
  'react_tension': require('../../assets/sprites/crowd/react_tension.png'),
} as const;

export const PLAYER_SPRITES = {
  'breathe': require('../../assets/sprites/player/breathe.png'),
  'defeated': require('../../assets/sprites/player/defeated.png'),
  'idle': require('../../assets/sprites/player/idle.png'),
  'victory': require('../../assets/sprites/player/victory.png'),
} as const;

export const LOTTERY_SPRITES = {
  'rank1': require('../../assets/sprites/lottery/rank1.png'),
  'rank2': require('../../assets/sprites/lottery/rank2.png'),
  'rank3': require('../../assets/sprites/lottery/rank3.png'),
  'rank4': require('../../assets/sprites/lottery/rank4.png'),
  'rank5': require('../../assets/sprites/lottery/rank5.png'),
  'ticket_clover': require('../../assets/sprites/lottery/ticket_clover.png'),
  'ticket_plain': require('../../assets/sprites/lottery/ticket_plain.png'),
  'ticket_torn': require('../../assets/sprites/lottery/ticket_torn.png'),
  'ticket_torn2': require('../../assets/sprites/lottery/ticket_torn2.png'),
} as const;

export const FX_SPRITES = {
  'burst_1': require('../../assets/sprites/fx/burst_1.png'),
  'burst_2': require('../../assets/sprites/fx/burst_2.png'),
  'burst_3': require('../../assets/sprites/fx/burst_3.png'),
  'burst_4': require('../../assets/sprites/fx/burst_4.png'),
  'burst_5': require('../../assets/sprites/fx/burst_5.png'),
  'glow_1': require('../../assets/sprites/fx/glow_1.png'),
  'glow_2': require('../../assets/sprites/fx/glow_2.png'),
  'glow_3': require('../../assets/sprites/fx/glow_3.png'),
  'glow_4': require('../../assets/sprites/fx/glow_4.png'),
  'glow_5': require('../../assets/sprites/fx/glow_5.png'),
  'shatter_1': require('../../assets/sprites/fx/shatter_1.png'),
  'shatter_2': require('../../assets/sprites/fx/shatter_2.png'),
  'shatter_3': require('../../assets/sprites/fx/shatter_3.png'),
  'shatter_4': require('../../assets/sprites/fx/shatter_4.png'),
  'shatter_5': require('../../assets/sprites/fx/shatter_5.png'),
  'smoke_1': require('../../assets/sprites/fx/smoke_1.png'),
  'smoke_2': require('../../assets/sprites/fx/smoke_2.png'),
  'smoke_3': require('../../assets/sprites/fx/smoke_3.png'),
  'smoke_4': require('../../assets/sprites/fx/smoke_4.png'),
  'smoke_5': require('../../assets/sprites/fx/smoke_5.png'),
} as const;

export const TIERFRAME_SPRITES = {
  '_alt10': require('../../assets/sprites/tierframe/_alt10.png'),
  '_alt4': require('../../assets/sprites/tierframe/_alt4.png'),
  '_alt8': require('../../assets/sprites/tierframe/_alt8.png'),
  't1': require('../../assets/sprites/tierframe/t1.png'),
  't10': require('../../assets/sprites/tierframe/t10.png'),
  't11': require('../../assets/sprites/tierframe/t11.png'),
  't2': require('../../assets/sprites/tierframe/t2.png'),
  't3': require('../../assets/sprites/tierframe/t3.png'),
  't4': require('../../assets/sprites/tierframe/t4.png'),
  't5': require('../../assets/sprites/tierframe/t5.png'),
  't6': require('../../assets/sprites/tierframe/t6.png'),
  't7': require('../../assets/sprites/tierframe/t7.png'),
  't8': require('../../assets/sprites/tierframe/t8.png'),
  't9': require('../../assets/sprites/tierframe/t9.png'),
} as const;

export const SLOT_SPRITES = {
  '_bracer': require('../../assets/sprites/slot/_bracer.png'),
  '_ear2': require('../../assets/sprites/slot/_ear2.png'),
  'belt': require('../../assets/sprites/slot/belt.png'),
  'boot': require('../../assets/sprites/slot/boot.png'),
  'chest': require('../../assets/sprites/slot/chest.png'),
  'ear': require('../../assets/sprites/slot/ear.png'),
  'glove': require('../../assets/sprites/slot/glove.png'),
  'greaves': require('../../assets/sprites/slot/greaves.png'),
  'helm': require('../../assets/sprites/slot/helm.png'),
  'neck': require('../../assets/sprites/slot/neck.png'),
  'ring': require('../../assets/sprites/slot/ring.png'),
  'sword': require('../../assets/sprites/slot/sword.png'),
} as const;

export const EQ_SPEAR_SPRITES = {
  't1': require('../../assets/sprites/eq_spear/t1.png'),
  't10': require('../../assets/sprites/eq_spear/t10.png'),
  't11': require('../../assets/sprites/eq_spear/t11.png'),
  't2': require('../../assets/sprites/eq_spear/t2.png'),
  't3': require('../../assets/sprites/eq_spear/t3.png'),
  't4': require('../../assets/sprites/eq_spear/t4.png'),
  't5': require('../../assets/sprites/eq_spear/t5.png'),
  't6': require('../../assets/sprites/eq_spear/t6.png'),
  't7': require('../../assets/sprites/eq_spear/t7.png'),
  't8': require('../../assets/sprites/eq_spear/t8.png'),
  't9': require('../../assets/sprites/eq_spear/t9.png'),
} as const;

export const EQ_BLADE_SPRITES = {
  't1': require('../../assets/sprites/eq_blade/t1.png'),
  't10': require('../../assets/sprites/eq_blade/t10.png'),
  't11': require('../../assets/sprites/eq_blade/t11.png'),
  't2': require('../../assets/sprites/eq_blade/t2.png'),
  't3': require('../../assets/sprites/eq_blade/t3.png'),
  't4': require('../../assets/sprites/eq_blade/t4.png'),
  't5': require('../../assets/sprites/eq_blade/t5.png'),
  't6': require('../../assets/sprites/eq_blade/t6.png'),
  't7': require('../../assets/sprites/eq_blade/t7.png'),
  't8': require('../../assets/sprites/eq_blade/t8.png'),
  't9': require('../../assets/sprites/eq_blade/t9.png'),
} as const;

export const EQ_MACE_SPRITES = {
  't1': require('../../assets/sprites/eq_mace/t1.png'),
  't10': require('../../assets/sprites/eq_mace/t10.png'),
  't11': require('../../assets/sprites/eq_mace/t11.png'),
  't2': require('../../assets/sprites/eq_mace/t2.png'),
  't3': require('../../assets/sprites/eq_mace/t3.png'),
  't4': require('../../assets/sprites/eq_mace/t4.png'),
  't5': require('../../assets/sprites/eq_mace/t5.png'),
  't6': require('../../assets/sprites/eq_mace/t6.png'),
  't7': require('../../assets/sprites/eq_mace/t7.png'),
  't8': require('../../assets/sprites/eq_mace/t8.png'),
  't9': require('../../assets/sprites/eq_mace/t9.png'),
} as const;

export const EQ_HAMMER_SPRITES = {
  't1': require('../../assets/sprites/eq_hammer/t1.png'),
  't10': require('../../assets/sprites/eq_hammer/t10.png'),
  't11': require('../../assets/sprites/eq_hammer/t11.png'),
  't2': require('../../assets/sprites/eq_hammer/t2.png'),
  't3': require('../../assets/sprites/eq_hammer/t3.png'),
  't4': require('../../assets/sprites/eq_hammer/t4.png'),
  't5': require('../../assets/sprites/eq_hammer/t5.png'),
  't6': require('../../assets/sprites/eq_hammer/t6.png'),
  't7': require('../../assets/sprites/eq_hammer/t7.png'),
  't8': require('../../assets/sprites/eq_hammer/t8.png'),
  't9': require('../../assets/sprites/eq_hammer/t9.png'),
} as const;

export const EQ_BOW_SPRITES = {
  't1': require('../../assets/sprites/eq_bow/t1.png'),
  't10': require('../../assets/sprites/eq_bow/t10.png'),
  't11': require('../../assets/sprites/eq_bow/t11.png'),
  't2': require('../../assets/sprites/eq_bow/t2.png'),
  't3': require('../../assets/sprites/eq_bow/t3.png'),
  't4': require('../../assets/sprites/eq_bow/t4.png'),
  't5': require('../../assets/sprites/eq_bow/t5.png'),
  't6': require('../../assets/sprites/eq_bow/t6.png'),
  't7': require('../../assets/sprites/eq_bow/t7.png'),
  't8': require('../../assets/sprites/eq_bow/t8.png'),
  't9': require('../../assets/sprites/eq_bow/t9.png'),
} as const;

export const EQ_STAFF_SPRITES = {
  't1': require('../../assets/sprites/eq_staff/t1.png'),
  't10': require('../../assets/sprites/eq_staff/t10.png'),
  't11': require('../../assets/sprites/eq_staff/t11.png'),
  't2': require('../../assets/sprites/eq_staff/t2.png'),
  't3': require('../../assets/sprites/eq_staff/t3.png'),
  't4': require('../../assets/sprites/eq_staff/t4.png'),
  't5': require('../../assets/sprites/eq_staff/t5.png'),
  't6': require('../../assets/sprites/eq_staff/t6.png'),
  't7': require('../../assets/sprites/eq_staff/t7.png'),
  't8': require('../../assets/sprites/eq_staff/t8.png'),
  't9': require('../../assets/sprites/eq_staff/t9.png'),
} as const;

export const EQ_BOOT_SPRITES = {
  't1': require('../../assets/sprites/eq_boot/t1.png'),
  't10': require('../../assets/sprites/eq_boot/t10.png'),
  't11': require('../../assets/sprites/eq_boot/t11.png'),
  't2': require('../../assets/sprites/eq_boot/t2.png'),
  't3': require('../../assets/sprites/eq_boot/t3.png'),
  't4': require('../../assets/sprites/eq_boot/t4.png'),
  't5': require('../../assets/sprites/eq_boot/t5.png'),
  't6': require('../../assets/sprites/eq_boot/t6.png'),
  't7': require('../../assets/sprites/eq_boot/t7.png'),
  't8': require('../../assets/sprites/eq_boot/t8.png'),
  't9': require('../../assets/sprites/eq_boot/t9.png'),
} as const;

export const EQ_EAR_SPRITES = {
  't1': require('../../assets/sprites/eq_ear/t1.png'),
  't10': require('../../assets/sprites/eq_ear/t10.png'),
  't11': require('../../assets/sprites/eq_ear/t11.png'),
  't2': require('../../assets/sprites/eq_ear/t2.png'),
  't3': require('../../assets/sprites/eq_ear/t3.png'),
  't4': require('../../assets/sprites/eq_ear/t4.png'),
  't5': require('../../assets/sprites/eq_ear/t5.png'),
  't6': require('../../assets/sprites/eq_ear/t6.png'),
  't7': require('../../assets/sprites/eq_ear/t7.png'),
  't8': require('../../assets/sprites/eq_ear/t8.png'),
  't9': require('../../assets/sprites/eq_ear/t9.png'),
} as const;

export const EQ_RING_SPRITES = {
  't1': require('../../assets/sprites/eq_ring/t1.png'),
  't10': require('../../assets/sprites/eq_ring/t10.png'),
  't11': require('../../assets/sprites/eq_ring/t11.png'),
  't2': require('../../assets/sprites/eq_ring/t2.png'),
  't3': require('../../assets/sprites/eq_ring/t3.png'),
  't4': require('../../assets/sprites/eq_ring/t4.png'),
  't5': require('../../assets/sprites/eq_ring/t5.png'),
  't6': require('../../assets/sprites/eq_ring/t6.png'),
  't7': require('../../assets/sprites/eq_ring/t7.png'),
  't8': require('../../assets/sprites/eq_ring/t8.png'),
  't9': require('../../assets/sprites/eq_ring/t9.png'),
} as const;

export const EQ_BELT_SPRITES = {
  't1': require('../../assets/sprites/eq_belt/t1.png'),
  't10': require('../../assets/sprites/eq_belt/t10.png'),
  't11': require('../../assets/sprites/eq_belt/t11.png'),
  't2': require('../../assets/sprites/eq_belt/t2.png'),
  't3': require('../../assets/sprites/eq_belt/t3.png'),
  't4': require('../../assets/sprites/eq_belt/t4.png'),
  't5': require('../../assets/sprites/eq_belt/t5.png'),
  't6': require('../../assets/sprites/eq_belt/t6.png'),
  't7': require('../../assets/sprites/eq_belt/t7.png'),
  't8': require('../../assets/sprites/eq_belt/t8.png'),
  't9': require('../../assets/sprites/eq_belt/t9.png'),
} as const;

export const EQ_CHEST_SPRITES = {
  't1': require('../../assets/sprites/eq_chest/t1.png'),
  't10': require('../../assets/sprites/eq_chest/t10.png'),
  't11': require('../../assets/sprites/eq_chest/t11.png'),
  't2': require('../../assets/sprites/eq_chest/t2.png'),
  't3': require('../../assets/sprites/eq_chest/t3.png'),
  't4': require('../../assets/sprites/eq_chest/t4.png'),
  't5': require('../../assets/sprites/eq_chest/t5.png'),
  't6': require('../../assets/sprites/eq_chest/t6.png'),
  't7': require('../../assets/sprites/eq_chest/t7.png'),
  't8': require('../../assets/sprites/eq_chest/t8.png'),
  't9': require('../../assets/sprites/eq_chest/t9.png'),
} as const;

export const EQ_SWORD_SPRITES = {
  't1': require('../../assets/sprites/eq_sword/t1.png'),
  't10': require('../../assets/sprites/eq_sword/t10.png'),
  't11': require('../../assets/sprites/eq_sword/t11.png'),
  't2': require('../../assets/sprites/eq_sword/t2.png'),
  't3': require('../../assets/sprites/eq_sword/t3.png'),
  't4': require('../../assets/sprites/eq_sword/t4.png'),
  't5': require('../../assets/sprites/eq_sword/t5.png'),
  't6': require('../../assets/sprites/eq_sword/t6.png'),
  't7': require('../../assets/sprites/eq_sword/t7.png'),
  't8': require('../../assets/sprites/eq_sword/t8.png'),
  't9': require('../../assets/sprites/eq_sword/t9.png'),
} as const;

export const EQ_AXE_SPRITES = {
  't1': require('../../assets/sprites/eq_axe/t1.png'),
  't10': require('../../assets/sprites/eq_axe/t10.png'),
  't11': require('../../assets/sprites/eq_axe/t11.png'),
  't2': require('../../assets/sprites/eq_axe/t2.png'),
  't3': require('../../assets/sprites/eq_axe/t3.png'),
  't4': require('../../assets/sprites/eq_axe/t4.png'),
  't5': require('../../assets/sprites/eq_axe/t5.png'),
  't6': require('../../assets/sprites/eq_axe/t6.png'),
  't7': require('../../assets/sprites/eq_axe/t7.png'),
  't8': require('../../assets/sprites/eq_axe/t8.png'),
  't9': require('../../assets/sprites/eq_axe/t9.png'),
} as const;

export const EQ_CROSSBOW_SPRITES = {
  't1': require('../../assets/sprites/eq_crossbow/t1.png'),
  't10': require('../../assets/sprites/eq_crossbow/t10.png'),
  't11': require('../../assets/sprites/eq_crossbow/t11.png'),
  't2': require('../../assets/sprites/eq_crossbow/t2.png'),
  't3': require('../../assets/sprites/eq_crossbow/t3.png'),
  't4': require('../../assets/sprites/eq_crossbow/t4.png'),
  't5': require('../../assets/sprites/eq_crossbow/t5.png'),
  't6': require('../../assets/sprites/eq_crossbow/t6.png'),
  't7': require('../../assets/sprites/eq_crossbow/t7.png'),
  't8': require('../../assets/sprites/eq_crossbow/t8.png'),
  't9': require('../../assets/sprites/eq_crossbow/t9.png'),
} as const;

export const EQ_GREAVES_SPRITES = {
  't1': require('../../assets/sprites/eq_greaves/t1.png'),
  't10': require('../../assets/sprites/eq_greaves/t10.png'),
  't11': require('../../assets/sprites/eq_greaves/t11.png'),
  't2': require('../../assets/sprites/eq_greaves/t2.png'),
  't3': require('../../assets/sprites/eq_greaves/t3.png'),
  't4': require('../../assets/sprites/eq_greaves/t4.png'),
  't5': require('../../assets/sprites/eq_greaves/t5.png'),
  't6': require('../../assets/sprites/eq_greaves/t6.png'),
  't7': require('../../assets/sprites/eq_greaves/t7.png'),
  't8': require('../../assets/sprites/eq_greaves/t8.png'),
  't9': require('../../assets/sprites/eq_greaves/t9.png'),
} as const;

export const EQ_GLOVE_SPRITES = {
  't1': require('../../assets/sprites/eq_glove/t1.png'),
  't10': require('../../assets/sprites/eq_glove/t10.png'),
  't11': require('../../assets/sprites/eq_glove/t11.png'),
  't2': require('../../assets/sprites/eq_glove/t2.png'),
  't3': require('../../assets/sprites/eq_glove/t3.png'),
  't4': require('../../assets/sprites/eq_glove/t4.png'),
  't5': require('../../assets/sprites/eq_glove/t5.png'),
  't6': require('../../assets/sprites/eq_glove/t6.png'),
  't7': require('../../assets/sprites/eq_glove/t7.png'),
  't8': require('../../assets/sprites/eq_glove/t8.png'),
  't9': require('../../assets/sprites/eq_glove/t9.png'),
} as const;

export const EQ_ROD_SPRITES = {
  't1': require('../../assets/sprites/eq_rod/t1.png'),
  't10': require('../../assets/sprites/eq_rod/t10.png'),
  't11': require('../../assets/sprites/eq_rod/t11.png'),
  't2': require('../../assets/sprites/eq_rod/t2.png'),
  't3': require('../../assets/sprites/eq_rod/t3.png'),
  't4': require('../../assets/sprites/eq_rod/t4.png'),
  't5': require('../../assets/sprites/eq_rod/t5.png'),
  't6': require('../../assets/sprites/eq_rod/t6.png'),
  't7': require('../../assets/sprites/eq_rod/t7.png'),
  't8': require('../../assets/sprites/eq_rod/t8.png'),
  't9': require('../../assets/sprites/eq_rod/t9.png'),
} as const;

export const EQ_NECK_SPRITES = {
  't1': require('../../assets/sprites/eq_neck/t1.png'),
  't10': require('../../assets/sprites/eq_neck/t10.png'),
  't11': require('../../assets/sprites/eq_neck/t11.png'),
  't2': require('../../assets/sprites/eq_neck/t2.png'),
  't3': require('../../assets/sprites/eq_neck/t3.png'),
  't4': require('../../assets/sprites/eq_neck/t4.png'),
  't5': require('../../assets/sprites/eq_neck/t5.png'),
  't6': require('../../assets/sprites/eq_neck/t6.png'),
  't7': require('../../assets/sprites/eq_neck/t7.png'),
  't8': require('../../assets/sprites/eq_neck/t8.png'),
  't9': require('../../assets/sprites/eq_neck/t9.png'),
} as const;

export const EQ_FAN_SPRITES = {
  't1': require('../../assets/sprites/eq_fan/t1.png'),
  't10': require('../../assets/sprites/eq_fan/t10.png'),
  't11': require('../../assets/sprites/eq_fan/t11.png'),
  't2': require('../../assets/sprites/eq_fan/t2.png'),
  't3': require('../../assets/sprites/eq_fan/t3.png'),
  't4': require('../../assets/sprites/eq_fan/t4.png'),
  't5': require('../../assets/sprites/eq_fan/t5.png'),
  't6': require('../../assets/sprites/eq_fan/t6.png'),
  't7': require('../../assets/sprites/eq_fan/t7.png'),
  't8': require('../../assets/sprites/eq_fan/t8.png'),
  't9': require('../../assets/sprites/eq_fan/t9.png'),
} as const;

export const GUILD_SPRITES = {
  '01': require('../../assets/sprites/guild/01.png'),
  '02': require('../../assets/sprites/guild/02.png'),
  '03': require('../../assets/sprites/guild/03.png'),
  '04': require('../../assets/sprites/guild/04.png'),
  '05': require('../../assets/sprites/guild/05.png'),
  '06': require('../../assets/sprites/guild/06.png'),
  '07': require('../../assets/sprites/guild/07.png'),
  '08': require('../../assets/sprites/guild/08.png'),
  '09': require('../../assets/sprites/guild/09.png'),
  '10': require('../../assets/sprites/guild/10.png'),
  '11': require('../../assets/sprites/guild/11.png'),
  '12': require('../../assets/sprites/guild/12.png'),
  '13': require('../../assets/sprites/guild/13.png'),
  '14': require('../../assets/sprites/guild/14.png'),
  '15': require('../../assets/sprites/guild/15.png'),
} as const;

export const GUILD_UI_SPRITES = {
  'banner': require('../../assets/sprites/guild_ui/banner.png'),
  'chevron': require('../../assets/sprites/guild_ui/chevron.png'),
  'master': require('../../assets/sprites/guild_ui/master.png'),
  'member': require('../../assets/sprites/guild_ui/member.png'),
  'members': require('../../assets/sprites/guild_ui/members.png'),
  'rank1': require('../../assets/sprites/guild_ui/rank1.png'),
  'rank2': require('../../assets/sprites/guild_ui/rank2.png'),
  'rank3': require('../../assets/sprites/guild_ui/rank3.png'),
} as const;

export const EQ_HELM_SPRITES = {
  't1': require('../../assets/sprites/eq_helm/t1.png'),
  't10': require('../../assets/sprites/eq_helm/t10.png'),
  't11': require('../../assets/sprites/eq_helm/t11.png'),
  't2': require('../../assets/sprites/eq_helm/t2.png'),
  't3': require('../../assets/sprites/eq_helm/t3.png'),
  't4': require('../../assets/sprites/eq_helm/t4.png'),
  't5': require('../../assets/sprites/eq_helm/t5.png'),
  't6': require('../../assets/sprites/eq_helm/t6.png'),
  't7': require('../../assets/sprites/eq_helm/t7.png'),
  't8': require('../../assets/sprites/eq_helm/t8.png'),
  't9': require('../../assets/sprites/eq_helm/t9.png'),
} as const;

export const MAP_SPRITES = {
  'forest': require('../../assets/sprites/map/forest.png'),
  'rift': require('../../assets/sprites/map/rift.png'),
  'ruin': require('../../assets/sprites/map/ruin.png'),
  'sea': require('../../assets/sprites/map/sea.png'),
  'snow': require('../../assets/sprites/map/snow.png'),
  'town': require('../../assets/sprites/map/town.png'),
  'wild': require('../../assets/sprites/map/wild.png'),
} as const;

export const MAP_PIN_SPRITES = {
  'banner': require('../../assets/sprites/map_pin/banner.png'),
  'compass': require('../../assets/sprites/map_pin/compass.png'),
  'here': require('../../assets/sprites/map_pin/here.png'),
  'locked': require('../../assets/sprites/map_pin/locked.png'),
  'road_node': require('../../assets/sprites/map_pin/road_node.png'),
  'signpost': require('../../assets/sprites/map_pin/signpost.png'),
  'unvisited': require('../../assets/sprites/map_pin/unvisited.png'),
  'visited': require('../../assets/sprites/map_pin/visited.png'),
} as const;

export const BG_FOREST_SPRITES = {
  'deep': require('../../assets/sprites/bg_forest/deep.png'),
  'elf_house': require('../../assets/sprites/bg_forest/elf_house.png'),
  'elf_night': require('../../assets/sprites/bg_forest/elf_night.png'),
  'gate': require('../../assets/sprites/bg_forest/gate.png'),
  'spring': require('../../assets/sprites/bg_forest/spring.png'),
  'worldtree': require('../../assets/sprites/bg_forest/worldtree.png'),
} as const;

export const STONE_SPRITES = {
  'high_crack': require('../../assets/sprites/stone/high_crack.png'),
  'high_glow': require('../../assets/sprites/stone/high_glow.png'),
  'high_idle': require('../../assets/sprites/stone/high_idle.png'),
  'low_crack': require('../../assets/sprites/stone/low_crack.png'),
  'low_glow': require('../../assets/sprites/stone/low_glow.png'),
  'low_idle': require('../../assets/sprites/stone/low_idle.png'),
  'mid_crack': require('../../assets/sprites/stone/mid_crack.png'),
  'mid_glow': require('../../assets/sprites/stone/mid_glow.png'),
  'mid_idle': require('../../assets/sprites/stone/mid_idle.png'),
} as const;

export const GRADE_SPRITES = {
  'g1': require('../../assets/sprites/grade/g1.png'),
  'g2': require('../../assets/sprites/grade/g2.png'),
  'g3': require('../../assets/sprites/grade/g3.png'),
  'g4': require('../../assets/sprites/grade/g4.png'),
  'g5': require('../../assets/sprites/grade/g5.png'),
  'g6': require('../../assets/sprites/grade/g6.png'),
  'g7': require('../../assets/sprites/grade/g7.png'),
  'g8': require('../../assets/sprites/grade/g8.png'),
  'g9': require('../../assets/sprites/grade/g9.png'),
} as const;

export const FX_RUNE_SPRITES = {
  '1': require('../../assets/sprites/fx_rune/1.png'),
  '2': require('../../assets/sprites/fx_rune/2.png'),
  '3': require('../../assets/sprites/fx_rune/3.png'),
  '4': require('../../assets/sprites/fx_rune/4.png'),
  '5': require('../../assets/sprites/fx_rune/5.png'),
} as const;

export const SYNERGY_SPRITES = {
  'crown': require('../../assets/sprites/synergy/crown.png'),
  'leaf': require('../../assets/sprites/synergy/leaf.png'),
  'ring1': require('../../assets/sprites/synergy/ring1.png'),
  'ring2': require('../../assets/sprites/synergy/ring2.png'),
  'ring3': require('../../assets/sprites/synergy/ring3.png'),
  'rock': require('../../assets/sprites/synergy/rock.png'),
  'rune': require('../../assets/sprites/synergy/rune.png'),
  'wind': require('../../assets/sprites/synergy/wind.png'),
} as const;

export const TAB_SPRITES = {
  'collection': require('../../assets/sprites/tab/collection.png'),
  'etc': require('../../assets/sprites/tab/etc.png'),
  'home': require('../../assets/sprites/tab/home.png'),
  'money': require('../../assets/sprites/tab/money.png'),
  'town': require('../../assets/sprites/tab/town.png'),
} as const;

export const AUTH_SPRITES = {
  'google': require('../../assets/sprites/auth/google.png'),
  'guest': require('../../assets/sprites/auth/guest.png'),
  'hero': require('../../assets/sprites/auth/hero.png'),
  'quill': require('../../assets/sprites/auth/quill.png'),
} as const;

export const POTION_SPRITES = {
  'high': require('../../assets/sprites/potion/high.png'),
  'low': require('../../assets/sprites/potion/low.png'),
  'mid': require('../../assets/sprites/potion/mid.png'),
} as const;

export const ABYSSMAT_SPRITES = {
  'ash': require('../../assets/sprites/abyssmat/ash.png'),
  'core': require('../../assets/sprites/abyssmat/core.png'),
  'shard': require('../../assets/sprites/abyssmat/shard.png'),
} as const;

export const FAMILY_SPRITES = {
  'beast': require('../../assets/sprites/family/beast.png'),
  'fish': require('../../assets/sprites/family/fish.png'),
  'herb': require('../../assets/sprites/family/herb.png'),
  'mushroom': require('../../assets/sprites/family/mushroom.png'),
  'ore': require('../../assets/sprites/family/ore.png'),
} as const;

export const TOOL_SPRITES = {
  'fish': require('../../assets/sprites/tool/fish.png'),
  'fish_A': require('../../assets/sprites/tool/fish_A.png'),
  'fish_B': require('../../assets/sprites/tool/fish_B.png'),
  'fish_C': require('../../assets/sprites/tool/fish_C.png'),
  'fish_D': require('../../assets/sprites/tool/fish_D.png'),
  'fish_E': require('../../assets/sprites/tool/fish_E.png'),
  'fish_F': require('../../assets/sprites/tool/fish_F.png'),
  'fish_S': require('../../assets/sprites/tool/fish_S.png'),
  'gather': require('../../assets/sprites/tool/gather.png'),
  'gather_A': require('../../assets/sprites/tool/gather_A.png'),
  'gather_B': require('../../assets/sprites/tool/gather_B.png'),
  'gather_C': require('../../assets/sprites/tool/gather_C.png'),
  'gather_D': require('../../assets/sprites/tool/gather_D.png'),
  'gather_E': require('../../assets/sprites/tool/gather_E.png'),
  'gather_F': require('../../assets/sprites/tool/gather_F.png'),
  'gather_S': require('../../assets/sprites/tool/gather_S.png'),
  'hunt_A': require('../../assets/sprites/tool/hunt_A.png'),
  'hunt_B': require('../../assets/sprites/tool/hunt_B.png'),
  'hunt_C': require('../../assets/sprites/tool/hunt_C.png'),
  'hunt_D': require('../../assets/sprites/tool/hunt_D.png'),
  'hunt_E': require('../../assets/sprites/tool/hunt_E.png'),
  'hunt_F': require('../../assets/sprites/tool/hunt_F.png'),
  'hunt_S': require('../../assets/sprites/tool/hunt_S.png'),
} as const;

export const HOLO_SPRITES = {
  'body': require('../../assets/sprites/holo/body.png'),
  'body_x': require('../../assets/sprites/holo/body_x.png'),
  'bullet': require('../../assets/sprites/holo/bullet.png'),
  'head': require('../../assets/sprites/holo/head.png'),
  'head_x': require('../../assets/sprites/holo/head_x.png'),
  'ship': require('../../assets/sprites/holo/ship.png'),
  'tail': require('../../assets/sprites/holo/tail.png'),
  'tail_x': require('../../assets/sprites/holo/tail_x.png'),
} as const;

export const MINES_SPRITES = {
  'bomb': require('../../assets/sprites/mines/bomb.png'),
  'closed': require('../../assets/sprites/mines/closed.png'),
  'flag': require('../../assets/sprites/mines/flag.png'),
  'open': require('../../assets/sprites/mines/open.png'),
} as const;

export const SP_HERB_SPRITES = {
  'bandagemoss': require('../../assets/sprites/sp_herb/bandagemoss.png'),
  'bitterleaf': require('../../assets/sprites/sp_herb/bitterleaf.png'),
  'dewgrass': require('../../assets/sprites/sp_herb/dewgrass.png'),
  'dragonblood': require('../../assets/sprites/sp_herb/dragonblood.png'),
  'frostlily': require('../../assets/sprites/sp_herb/frostlily.png'),
  'moonflower': require('../../assets/sprites/sp_herb/moonflower.png'),
  'silverleaf': require('../../assets/sprites/sp_herb/silverleaf.png'),
  'spiritherb': require('../../assets/sprites/sp_herb/spiritherb.png'),
} as const;

export const SP_ORE_SPRITES = {
  'copperore': require('../../assets/sprites/sp_ore/copperore.png'),
  'goldore': require('../../assets/sprites/sp_ore/goldore.png'),
  'ironore': require('../../assets/sprites/sp_ore/ironore.png'),
  'mithrilbit': require('../../assets/sprites/sp_ore/mithrilbit.png'),
  'orichalcum': require('../../assets/sprites/sp_ore/orichalcum.png'),
  'pebble': require('../../assets/sprites/sp_ore/pebble.png'),
  'quartz': require('../../assets/sprites/sp_ore/quartz.png'),
  'silverore': require('../../assets/sprites/sp_ore/silverore.png'),
} as const;

export const SP_MUSHROOM_SPRITES = {
  'abyssspore': require('../../assets/sprites/sp_mushroom/abyssspore.png'),
  'dirtcap': require('../../assets/sprites/sp_mushroom/dirtcap.png'),
  'dreamcap': require('../../assets/sprites/sp_mushroom/dreamcap.png'),
  'lampcap': require('../../assets/sprites/sp_mushroom/lampcap.png'),
  'moldcap': require('../../assets/sprites/sp_mushroom/moldcap.png'),
  'panaceacap': require('../../assets/sprites/sp_mushroom/panaceacap.png'),
  'poisonbrolly': require('../../assets/sprites/sp_mushroom/poisonbrolly.png'),
  'spiritcap': require('../../assets/sprites/sp_mushroom/spiritcap.png'),
} as const;

export const SP_BEAST_SPRITES = {
  'blackbear': require('../../assets/sprites/sp_beast/blackbear.png'),
  'boar': require('../../assets/sprites/sp_beast/boar.png'),
  'fieldrat': require('../../assets/sprites/sp_beast/fieldrat.png'),
  'greywolf': require('../../assets/sprites/sp_beast/greywolf.png'),
  'hare': require('../../assets/sprites/sp_beast/hare.png'),
  'hornlessdeer': require('../../assets/sprites/sp_beast/hornlessdeer.png'),
  'icefox': require('../../assets/sprites/sp_beast/icefox.png'),
  'oneeyedowl': require('../../assets/sprites/sp_beast/oneeyedowl.png'),
  'onehornogre': require('../../assets/sprites/sp_beast/onehornogre.png'),
  'shadowpanther': require('../../assets/sprites/sp_beast/shadowpanther.png'),
  'spinytoad': require('../../assets/sprites/sp_beast/spinytoad.png'),
  'steelmantis': require('../../assets/sprites/sp_beast/steelmantis.png'),
} as const;

export const SP_FISH_SPRITES = {
  'abysseel': require('../../assets/sprites/sp_fish/abysseel.png'),
  'centuryturtle': require('../../assets/sprites/sp_fish/centuryturtle.png'),
  'dragonsturgeon': require('../../assets/sprites/sp_fish/dragonsturgeon.png'),
  'icetrout': require('../../assets/sprites/sp_fish/icetrout.png'),
  'ironcarp': require('../../assets/sprites/sp_fish/ironcarp.png'),
  'lampangler': require('../../assets/sprites/sp_fish/lampangler.png'),
  'minnow': require('../../assets/sprites/sp_fish/minnow.png'),
  'moonray': require('../../assets/sprites/sp_fish/moonray.png'),
  'mudcarp': require('../../assets/sprites/sp_fish/mudcarp.png'),
  'riverpike': require('../../assets/sprites/sp_fish/riverpike.png'),
  'silverscale': require('../../assets/sprites/sp_fish/silverscale.png'),
  'spiritwhale': require('../../assets/sprites/sp_fish/spiritwhale.png'),
  'whirltuna': require('../../assets/sprites/sp_fish/whirltuna.png'),
  'whiskercat': require('../../assets/sprites/sp_fish/whiskercat.png'),
} as const;

export const FOOD_SPRITES = {
  'booze': require('../../assets/sprites/food/booze.png'),
  'bread': require('../../assets/sprites/food/bread.png'),
  'stew': require('../../assets/sprites/food/stew.png'),
  'water': require('../../assets/sprites/food/water.png'),
} as const;

export const MATERIAL_SPRITES = {
  'bone': require('../../assets/sprites/material/bone.png'),
  'skin': require('../../assets/sprites/material/skin.png'),
  'tooth': require('../../assets/sprites/material/tooth.png'),
} as const;

export const DUEL_SPRITES = {
  'guard': require('../../assets/sprites/duel/guard.png'),
  'hit': require('../../assets/sprites/duel/hit.png'),
  'lose': require('../../assets/sprites/duel/lose.png'),
  'recover': require('../../assets/sprites/duel/recover.png'),
  'stagger': require('../../assets/sprites/duel/stagger.png'),
  'strike': require('../../assets/sprites/duel/strike.png'),
  'win': require('../../assets/sprites/duel/win.png'),
  'windup': require('../../assets/sprites/duel/windup.png'),
} as const;

export const TUTORIAL_SPRITES = {
  'check': require('../../assets/sprites/tutorial/check.png'),
  'drag': require('../../assets/sprites/tutorial/drag.png'),
  'hint': require('../../assets/sprites/tutorial/hint.png'),
  'point_down': require('../../assets/sprites/tutorial/point_down.png'),
  'point_left': require('../../assets/sprites/tutorial/point_left.png'),
  'point_right': require('../../assets/sprites/tutorial/point_right.png'),
  'point_up': require('../../assets/sprites/tutorial/point_up.png'),
  'skip': require('../../assets/sprites/tutorial/skip.png'),
  'tap': require('../../assets/sprites/tutorial/tap.png'),
  'warn': require('../../assets/sprites/tutorial/warn.png'),
} as const;

export const RAID_BOSS_SPRITES = {
  'd01': require('../../assets/sprites/raid_boss/d01.png'),
  'd02': require('../../assets/sprites/raid_boss/d02.png'),
  'd03': require('../../assets/sprites/raid_boss/d03.png'),
  'd04': require('../../assets/sprites/raid_boss/d04.png'),
  'd05': require('../../assets/sprites/raid_boss/d05.png'),
  'd06': require('../../assets/sprites/raid_boss/d06.png'),
  'd07': require('../../assets/sprites/raid_boss/d07.png'),
  'd08': require('../../assets/sprites/raid_boss/d08.png'),
  'd09': require('../../assets/sprites/raid_boss/d09.png'),
  'd10': require('../../assets/sprites/raid_boss/d10.png'),
  's01': require('../../assets/sprites/raid_boss/s01.png'),
  's02': require('../../assets/sprites/raid_boss/s02.png'),
  's03': require('../../assets/sprites/raid_boss/s03.png'),
  'w01': require('../../assets/sprites/raid_boss/w01.png'),
  'w02': require('../../assets/sprites/raid_boss/w02.png'),
  'w03': require('../../assets/sprites/raid_boss/w03.png'),
} as const;

export const EVENT_SPRITES = {
  'attend': require('../../assets/sprites/event/attend.png'),
  'bonus': require('../../assets/sprites/event/bonus.png'),
  'ended': require('../../assets/sprites/event/ended.png'),
  'gift': require('../../assets/sprites/event/gift.png'),
  'notice': require('../../assets/sprites/event/notice.png'),
  'notice_alt': require('../../assets/sprites/event/notice_alt.png'),
  'season': require('../../assets/sprites/event/season.png'),
  'season_alt': require('../../assets/sprites/event/season_alt.png'),
} as const;

export const ELF_SPRITES = {
  'portrait': require('../../assets/sprites/elf/portrait.png'),
  'stand': require('../../assets/sprites/elf/stand.png'),
} as const;

export const SMITH_SPRITES = {
  'portrait': require('../../assets/sprites/smith/portrait.png'),
  'stand': require('../../assets/sprites/smith/stand.png'),
} as const;

export const MAID_SPRITES = {
  'happy': require('../../assets/sprites/maid/happy.png'),
  'portrait': require('../../assets/sprites/maid/portrait.png'),
  'shy': require('../../assets/sprites/maid/shy.png'),
  'stand': require('../../assets/sprites/maid/stand.png'),
} as const;

export const KNIGHTGIRL_SPRITES = {
  'cut_1': require('../../assets/sprites/knightgirl/cut_1.png'),
  'cut_2': require('../../assets/sprites/knightgirl/cut_2.png'),
  'cut_3': require('../../assets/sprites/knightgirl/cut_3.png'),
  'guard': require('../../assets/sprites/knightgirl/guard.png'),
  'hit': require('../../assets/sprites/knightgirl/hit.png'),
  'lose': require('../../assets/sprites/knightgirl/lose.png'),
  'recover': require('../../assets/sprites/knightgirl/recover.png'),
  'sk_1': require('../../assets/sprites/knightgirl/sk_1.png'),
  'sk_2': require('../../assets/sprites/knightgirl/sk_2.png'),
  'sk_3': require('../../assets/sprites/knightgirl/sk_3.png'),
  'stagger': require('../../assets/sprites/knightgirl/stagger.png'),
  'strike': require('../../assets/sprites/knightgirl/strike.png'),
  'win': require('../../assets/sprites/knightgirl/win.png'),
  'windup': require('../../assets/sprites/knightgirl/windup.png'),
} as const;

export const KNIGHTGIRL_WAVE_SPRITES = {
  'wave_1': require('../../assets/sprites/knightgirl_wave/wave_1.png'),
  'wave_2': require('../../assets/sprites/knightgirl_wave/wave_2.png'),
  'wave_3': require('../../assets/sprites/knightgirl_wave/wave_3.png'),
} as const;

export const BUNNYAXE_SPRITES = {
  'cut_1': require('../../assets/sprites/bunnyaxe/cut_1.png'),
  'cut_2': require('../../assets/sprites/bunnyaxe/cut_2.png'),
  'cut_3': require('../../assets/sprites/bunnyaxe/cut_3.png'),
  'guard': require('../../assets/sprites/bunnyaxe/guard.png'),
  'hit': require('../../assets/sprites/bunnyaxe/hit.png'),
  'lose': require('../../assets/sprites/bunnyaxe/lose.png'),
  'recover': require('../../assets/sprites/bunnyaxe/recover.png'),
  'sk_1': require('../../assets/sprites/bunnyaxe/sk_1.png'),
  'sk_2': require('../../assets/sprites/bunnyaxe/sk_2.png'),
  'sk_3': require('../../assets/sprites/bunnyaxe/sk_3.png'),
  'stagger': require('../../assets/sprites/bunnyaxe/stagger.png'),
  'strike': require('../../assets/sprites/bunnyaxe/strike.png'),
  'win': require('../../assets/sprites/bunnyaxe/win.png'),
  'windup': require('../../assets/sprites/bunnyaxe/windup.png'),
} as const;

export const ELFARCHER_SPRITES = {
  'cut_1': require('../../assets/sprites/elfarcher/cut_1.png'),
  'cut_2': require('../../assets/sprites/elfarcher/cut_2.png'),
  'cut_3': require('../../assets/sprites/elfarcher/cut_3.png'),
  'guard': require('../../assets/sprites/elfarcher/guard.png'),
  'hit': require('../../assets/sprites/elfarcher/hit.png'),
  'lose': require('../../assets/sprites/elfarcher/lose.png'),
  'recover': require('../../assets/sprites/elfarcher/recover.png'),
  'sk_1': require('../../assets/sprites/elfarcher/sk_1.png'),
  'sk_2': require('../../assets/sprites/elfarcher/sk_2.png'),
  'sk_3': require('../../assets/sprites/elfarcher/sk_3.png'),
  'stagger': require('../../assets/sprites/elfarcher/stagger.png'),
  'strike': require('../../assets/sprites/elfarcher/strike.png'),
  'win': require('../../assets/sprites/elfarcher/win.png'),
  'windup': require('../../assets/sprites/elfarcher/windup.png'),
} as const;

export const ELFARCHER_SHOT_SPRITES = {
  'shot_1': require('../../assets/sprites/elfarcher_shot/shot_1.png'),
  'shot_2': require('../../assets/sprites/elfarcher_shot/shot_2.png'),
  'shot_3': require('../../assets/sprites/elfarcher_shot/shot_3.png'),
} as const;

export const NUN_SPRITES = {
  'cut_1': require('../../assets/sprites/nun/cut_1.png'),
  'cut_2': require('../../assets/sprites/nun/cut_2.png'),
  'cut_3': require('../../assets/sprites/nun/cut_3.png'),
  'guard': require('../../assets/sprites/nun/guard.png'),
  'hit': require('../../assets/sprites/nun/hit.png'),
  'lose': require('../../assets/sprites/nun/lose.png'),
  'recover': require('../../assets/sprites/nun/recover.png'),
  'sk_1': require('../../assets/sprites/nun/sk_1.png'),
  'sk_2': require('../../assets/sprites/nun/sk_2.png'),
  'sk_3': require('../../assets/sprites/nun/sk_3.png'),
  'stagger': require('../../assets/sprites/nun/stagger.png'),
  'strike': require('../../assets/sprites/nun/strike.png'),
  'win': require('../../assets/sprites/nun/win.png'),
  'windup': require('../../assets/sprites/nun/windup.png'),
} as const;

export const NUN_WAVE_SPRITES = {
  'wave_1': require('../../assets/sprites/nun_wave/wave_1.png'),
  'wave_2': require('../../assets/sprites/nun_wave/wave_2.png'),
  'wave_3': require('../../assets/sprites/nun_wave/wave_3.png'),
} as const;

export const SL_MELEE_SPRITES = {
  'attack': require('../../assets/sprites/sl_melee/attack.png'),
  'down': require('../../assets/sprites/sl_melee/down.png'),
  'idle': require('../../assets/sprites/sl_melee/idle.png'),
} as const;

export const SL_RANGED_SPRITES = {
  'attack': require('../../assets/sprites/sl_ranged/attack.png'),
  'down': require('../../assets/sprites/sl_ranged/down.png'),
  'idle': require('../../assets/sprites/sl_ranged/idle.png'),
} as const;

export const SL_BOSS_SPRITES = {
  'attack': require('../../assets/sprites/sl_boss/attack.png'),
  'down': require('../../assets/sprites/sl_boss/down.png'),
  'idle': require('../../assets/sprites/sl_boss/idle.png'),
} as const;

export const ROLE_ICON_SPRITES = {
  'role_melee': require('../../assets/sprites/role_icon/role_melee.png'),
  'role_ranged': require('../../assets/sprites/role_icon/role_ranged.png'),
  'role_support': require('../../assets/sprites/role_icon/role_support.png'),
  'role_tank': require('../../assets/sprites/role_icon/role_tank.png'),
} as const;

export const SKILL_ICON_SPRITES = {
  'sk_heal': require('../../assets/sprites/skill_icon/sk_heal.png'),
  'sk_leap': require('../../assets/sprites/skill_icon/sk_leap.png'),
  'sk_rain': require('../../assets/sprites/skill_icon/sk_rain.png'),
  'sk_wave': require('../../assets/sprites/skill_icon/sk_wave.png'),
} as const;

export const SG_GRASS_SPRITES = {
  'attack': require('../../assets/sprites/sg_grass/attack.png'),
  'down': require('../../assets/sprites/sg_grass/down.png'),
  'idle': require('../../assets/sprites/sg_grass/idle.png'),
} as const;

export const SG_MUD_SPRITES = {
  'attack': require('../../assets/sprites/sg_mud/attack.png'),
  'down': require('../../assets/sprites/sg_mud/down.png'),
  'idle': require('../../assets/sprites/sg_mud/idle.png'),
} as const;

export const SG_STONE_SPRITES = {
  'attack': require('../../assets/sprites/sg_stone/attack.png'),
  'down': require('../../assets/sprites/sg_stone/down.png'),
  'idle': require('../../assets/sprites/sg_stone/idle.png'),
} as const;

export const SG_BONE_SPRITES = {
  'attack': require('../../assets/sprites/sg_bone/attack.png'),
  'down': require('../../assets/sprites/sg_bone/down.png'),
  'idle': require('../../assets/sprites/sg_bone/idle.png'),
} as const;

export const SG_TWIN_SPRITES = {
  'attack': require('../../assets/sprites/sg_twin/attack.png'),
  'down': require('../../assets/sprites/sg_twin/down.png'),
  'idle': require('../../assets/sprites/sg_twin/idle.png'),
} as const;

export const SG_SPORE_SPRITES = {
  'attack': require('../../assets/sprites/sg_spore/attack.png'),
  'down': require('../../assets/sprites/sg_spore/down.png'),
  'idle': require('../../assets/sprites/sg_spore/idle.png'),
} as const;

export const SG_THORN_SPRITES = {
  'attack': require('../../assets/sprites/sg_thorn/attack.png'),
  'down': require('../../assets/sprites/sg_thorn/down.png'),
  'idle': require('../../assets/sprites/sg_thorn/idle.png'),
} as const;

export const SG_ACID_SPRITES = {
  'attack': require('../../assets/sprites/sg_acid/attack.png'),
  'down': require('../../assets/sprites/sg_acid/down.png'),
  'idle': require('../../assets/sprites/sg_acid/idle.png'),
} as const;

export const SB_GRASS_SPRITES = {
  'attack': require('../../assets/sprites/sb_grass/attack.png'),
  'down': require('../../assets/sprites/sb_grass/down.png'),
  'idle': require('../../assets/sprites/sb_grass/idle.png'),
} as const;

export const SB_MUD_SPRITES = {
  'attack': require('../../assets/sprites/sb_mud/attack.png'),
  'down': require('../../assets/sprites/sb_mud/down.png'),
  'idle': require('../../assets/sprites/sb_mud/idle.png'),
} as const;

export const SB_SPORE_SPRITES = {
  'attack': require('../../assets/sprites/sb_spore/attack.png'),
  'down': require('../../assets/sprites/sb_spore/down.png'),
  'idle': require('../../assets/sprites/sb_spore/idle.png'),
} as const;

export const SB_THORN_SPRITES = {
  'attack': require('../../assets/sprites/sb_thorn/attack.png'),
  'down': require('../../assets/sprites/sb_thorn/down.png'),
  'idle': require('../../assets/sprites/sb_thorn/idle.png'),
} as const;

export const SB_STONE_SPRITES = {
  'attack': require('../../assets/sprites/sb_stone/attack.png'),
  'down': require('../../assets/sprites/sb_stone/down.png'),
  'idle': require('../../assets/sprites/sb_stone/idle.png'),
} as const;

export const SB_TWIN_SPRITES = {
  'attack': require('../../assets/sprites/sb_twin/attack.png'),
  'down': require('../../assets/sprites/sb_twin/down.png'),
  'idle': require('../../assets/sprites/sb_twin/idle.png'),
} as const;

export const SB_ACID_SPRITES = {
  'attack': require('../../assets/sprites/sb_acid/attack.png'),
  'down': require('../../assets/sprites/sb_acid/down.png'),
  'idle': require('../../assets/sprites/sb_acid/idle.png'),
} as const;

export const SB_BONE_SPRITES = {
  'attack': require('../../assets/sprites/sb_bone/attack.png'),
  'down': require('../../assets/sprites/sb_bone/down.png'),
  'idle': require('../../assets/sprites/sb_bone/idle.png'),
} as const;

export const SB_KING_SPRITES = {
  'attack': require('../../assets/sprites/sb_king/attack.png'),
  'down': require('../../assets/sprites/sb_king/down.png'),
  'idle': require('../../assets/sprites/sb_king/idle.png'),
} as const;

export type SpriteSet = 'scroll' | 'weapon' | 'attend' | 'gear' | 'card' | 'title' | 'bubble' | 'jackpot' | 'creature' | 'cr_slime' | 'cr_wolf' | 'cr_golem' | 'cr_bat' | 'cr_boar' | 'cr_skeleton' | 'cr_toad' | 'cr_mantis' | 'cr_ogre' | 'cr_tentacle' | 'bg_chapter' | 'bg_place' | 'job' | 'avatar' | 'single_icon' | 'single_icon_alt' | 'single_splash' | 'pl_attack' | 'card_back' | 'coin' | 'crowd' | 'player' | 'lottery' | 'fx' | 'tierframe' | 'slot' | 'eq_spear' | 'eq_blade' | 'eq_mace' | 'eq_hammer' | 'eq_bow' | 'eq_staff' | 'eq_boot' | 'eq_ear' | 'eq_ring' | 'eq_belt' | 'eq_chest' | 'eq_sword' | 'eq_axe' | 'eq_crossbow' | 'eq_greaves' | 'eq_glove' | 'eq_rod' | 'eq_neck' | 'eq_fan' | 'guild' | 'guild_ui' | 'eq_helm' | 'map' | 'map_pin' | 'bg_forest' | 'stone' | 'grade' | 'fx_rune' | 'synergy' | 'tab' | 'auth' | 'potion' | 'abyssmat' | 'family' | 'tool' | 'holo' | 'mines' | 'sp_herb' | 'sp_ore' | 'sp_mushroom' | 'sp_beast' | 'sp_fish' | 'food' | 'material' | 'duel' | 'tutorial' | 'raid_boss' | 'event' | 'elf' | 'smith' | 'maid' | 'knightgirl' | 'knightgirl_wave' | 'bunnyaxe' | 'elfarcher' | 'elfarcher_shot' | 'nun' | 'nun_wave' | 'sl_melee' | 'sl_ranged' | 'sl_boss' | 'role_icon' | 'skill_icon' | 'sg_grass' | 'sg_mud' | 'sg_stone' | 'sg_bone' | 'sg_twin' | 'sg_spore' | 'sg_thorn' | 'sg_acid' | 'sb_grass' | 'sb_mud' | 'sb_spore' | 'sb_thorn' | 'sb_stone' | 'sb_twin' | 'sb_acid' | 'sb_bone' | 'sb_king';

export const SPRITES: Record<SpriteSet, Record<string, number>> = {
  scroll: SCROLL_SPRITES,
  weapon: WEAPON_SPRITES,
  attend: ATTEND_SPRITES,
  gear: GEAR_SPRITES,
  card: CARD_SPRITES,
  title: TITLE_SPRITES,
  bubble: BUBBLE_SPRITES,
  jackpot: JACKPOT_SPRITES,
  creature: CREATURE_SPRITES,
  cr_slime: CR_SLIME_SPRITES,
  cr_wolf: CR_WOLF_SPRITES,
  cr_golem: CR_GOLEM_SPRITES,
  cr_bat: CR_BAT_SPRITES,
  cr_boar: CR_BOAR_SPRITES,
  cr_skeleton: CR_SKELETON_SPRITES,
  cr_toad: CR_TOAD_SPRITES,
  cr_mantis: CR_MANTIS_SPRITES,
  cr_ogre: CR_OGRE_SPRITES,
  cr_tentacle: CR_TENTACLE_SPRITES,
  bg_chapter: BG_CHAPTER_SPRITES,
  bg_place: BG_PLACE_SPRITES,
  job: JOB_SPRITES,
  avatar: AVATAR_SPRITES,
  single_icon: SINGLE_ICON_SPRITES,
  single_icon_alt: SINGLE_ICON_ALT_SPRITES,
  single_splash: SINGLE_SPLASH_SPRITES,
  pl_attack: PL_ATTACK_SPRITES,
  card_back: CARD_BACK_SPRITES,
  coin: COIN_SPRITES,
  crowd: CROWD_SPRITES,
  player: PLAYER_SPRITES,
  lottery: LOTTERY_SPRITES,
  fx: FX_SPRITES,
  tierframe: TIERFRAME_SPRITES,
  slot: SLOT_SPRITES,
  eq_spear: EQ_SPEAR_SPRITES,
  eq_blade: EQ_BLADE_SPRITES,
  eq_mace: EQ_MACE_SPRITES,
  eq_hammer: EQ_HAMMER_SPRITES,
  eq_bow: EQ_BOW_SPRITES,
  eq_staff: EQ_STAFF_SPRITES,
  eq_boot: EQ_BOOT_SPRITES,
  eq_ear: EQ_EAR_SPRITES,
  eq_ring: EQ_RING_SPRITES,
  eq_belt: EQ_BELT_SPRITES,
  eq_chest: EQ_CHEST_SPRITES,
  eq_sword: EQ_SWORD_SPRITES,
  eq_axe: EQ_AXE_SPRITES,
  eq_crossbow: EQ_CROSSBOW_SPRITES,
  eq_greaves: EQ_GREAVES_SPRITES,
  eq_glove: EQ_GLOVE_SPRITES,
  eq_rod: EQ_ROD_SPRITES,
  eq_neck: EQ_NECK_SPRITES,
  eq_fan: EQ_FAN_SPRITES,
  guild: GUILD_SPRITES,
  guild_ui: GUILD_UI_SPRITES,
  eq_helm: EQ_HELM_SPRITES,
  map: MAP_SPRITES,
  map_pin: MAP_PIN_SPRITES,
  bg_forest: BG_FOREST_SPRITES,
  stone: STONE_SPRITES,
  grade: GRADE_SPRITES,
  fx_rune: FX_RUNE_SPRITES,
  synergy: SYNERGY_SPRITES,
  tab: TAB_SPRITES,
  auth: AUTH_SPRITES,
  potion: POTION_SPRITES,
  abyssmat: ABYSSMAT_SPRITES,
  family: FAMILY_SPRITES,
  tool: TOOL_SPRITES,
  holo: HOLO_SPRITES,
  mines: MINES_SPRITES,
  sp_herb: SP_HERB_SPRITES,
  sp_ore: SP_ORE_SPRITES,
  sp_mushroom: SP_MUSHROOM_SPRITES,
  sp_beast: SP_BEAST_SPRITES,
  sp_fish: SP_FISH_SPRITES,
  food: FOOD_SPRITES,
  material: MATERIAL_SPRITES,
  duel: DUEL_SPRITES,
  tutorial: TUTORIAL_SPRITES,
  raid_boss: RAID_BOSS_SPRITES,
  event: EVENT_SPRITES,
  elf: ELF_SPRITES,
  smith: SMITH_SPRITES,
  maid: MAID_SPRITES,
  knightgirl: KNIGHTGIRL_SPRITES,
  knightgirl_wave: KNIGHTGIRL_WAVE_SPRITES,
  bunnyaxe: BUNNYAXE_SPRITES,
  elfarcher: ELFARCHER_SPRITES,
  elfarcher_shot: ELFARCHER_SHOT_SPRITES,
  nun: NUN_SPRITES,
  nun_wave: NUN_WAVE_SPRITES,
  sl_melee: SL_MELEE_SPRITES,
  sl_ranged: SL_RANGED_SPRITES,
  sl_boss: SL_BOSS_SPRITES,
  role_icon: ROLE_ICON_SPRITES,
  skill_icon: SKILL_ICON_SPRITES,
  sg_grass: SG_GRASS_SPRITES,
  sg_mud: SG_MUD_SPRITES,
  sg_stone: SG_STONE_SPRITES,
  sg_bone: SG_BONE_SPRITES,
  sg_twin: SG_TWIN_SPRITES,
  sg_spore: SG_SPORE_SPRITES,
  sg_thorn: SG_THORN_SPRITES,
  sg_acid: SG_ACID_SPRITES,
  sb_grass: SB_GRASS_SPRITES,
  sb_mud: SB_MUD_SPRITES,
  sb_spore: SB_SPORE_SPRITES,
  sb_thorn: SB_THORN_SPRITES,
  sb_stone: SB_STONE_SPRITES,
  sb_twin: SB_TWIN_SPRITES,
  sb_acid: SB_ACID_SPRITES,
  sb_bone: SB_BONE_SPRITES,
  sb_king: SB_KING_SPRITES,
};

/** 세트에서 키를 안전하게 꺼낸다. 없으면 undefined — 호출부가 대체 렌더를 하도록. */
export function sprite(set: SpriteSet, key: string): number | undefined {
  return SPRITES[set]?.[key];
}

/**
 * 아직 없는 폴더를 문자열로 조회한다 (예: 티어별 장비 `eq_sword`).
 * 아트가 도착하기 전에도 코드를 미리 붙여 둘 수 있게 하는 용도.
 */
export function spriteLoose(set: string, key: string): number | undefined {
  return (SPRITES as Record<string, Record<string, number>>)[set]?.[key];
}

/**
 * 그림의 **세로 비율** (높이 ÷ 폭).
 *
 * `Sprite` 는 정사각 상자에 `contain` 으로 그린다. 그래서 가로로 긴
 * 그림은 상자 안에서 **위아래 가운데**에 놓이고, 발밑에 빈 자리가 생긴다 —
 * 슬라임(192x128)이면 상자 높이의 17% 다.
 *
 * 그 빈 자리를 알아야 **발을 같은 높이에 맞출 수 있다.** 그냥 두면 한 줄에
 * 섞여 선 놈들의 발 높이가 종마다 달라, 네 자리의 계단이 흐트러진다.
 */
export const SPRITE_RATIO: Record<string, number> = {
  'abyssmat/ash': 0.9338,
  'abyssmat/core': 0.993,
  'abyssmat/shard': 2.2742,
  'attend/cal_empty': 1.0323,
  'attend/cal_missed': 1.0323,
  'attend/cal_stamped': 1.0323,
  'attend/cal_today': 1.1163,
  'attend/stamp_check': 1.0159,
  'attend/stamp_flame': 1.0378,
  'attend/stamp_moon': 1.0323,
  'attend/stamp_sun': 1.0323,
  'auth/google': 1.1583,
  'auth/guest': 1.4237,
  'auth/hero': 0.4688,
  'auth/quill': 1.5273,
  'avatar/archer': 0.9167,
  'avatar/baron': 0.8958,
  'avatar/bunnyaxe': 1.1034,
  'avatar/bunnyblade': 1.0,
  'avatar/deserter': 0.8854,
  'avatar/duelist': 0.8073,
  'avatar/elfarcher': 1.28,
  'avatar/knight': 0.8646,
  'avatar/knightgirl': 0.9635,
  'avatar/maidhammer': 0.974,
  'avatar/mercenary': 0.875,
  'avatar/merchant': 0.9115,
  'avatar/miner': 0.9115,
  'avatar/nun': 1.5868,
  'avatar/regular': 0.849,
  'avatar/robber': 0.849,
  'avatar/spearman': 0.9115,
  'avatar/swordsman': 0.8073,
  'avatar/witchgirl': 0.9792,
  'bg_chapter/01': 0.4688,
  'bg_chapter/02': 0.5938,
  'bg_forest/deep': 0.8021,
  'bg_forest/elf_house': 0.8073,
  'bg_forest/elf_night': 0.8073,
  'bg_forest/gate': 0.8073,
  'bg_forest/spring': 0.8073,
  'bg_forest/worldtree': 0.8073,
  'bg_place/abyss': 0.9583,
  'bg_place/alchemist': 0.9167,
  'bg_place/arena': 1.3521,
  'bg_place/artisan': 1.3617,
  'bg_place/beastwood': 0.7604,
  'bg_place/fish': 0.8854,
  'bg_place/gamble': 1.3617,
  'bg_place/gather': 0.9583,
  'bg_place/hill_house': 0.8021,
  'bg_place/house': 1.3521,
  'bg_place/hunt': 0.9896,
  'bg_place/mine': 1.3333,
  'bg_place/office': 0.8854,
  'bg_place/shop': 1.3617,
  'bg_place/tavern': 0.9896,
  'bg_place/tower': 1.3617,
  'bubble/conversation': 1.0667,
  'bubble/empty': 1.1034,
  'bubble/message': 1.1034,
  'bubble/typing': 1.1034,
  'bunnyaxe/cut_1': 1.2886,
  'bunnyaxe/cut_2': 1.0213,
  'bunnyaxe/cut_3': 1.0549,
  'bunnyaxe/guard': 1.6552,
  'bunnyaxe/hit': 1.2,
  'bunnyaxe/lose': 0.8021,
  'bunnyaxe/recover': 1.2387,
  'bunnyaxe/sk_1': 1.0492,
  'bunnyaxe/sk_2': 1.4015,
  'bunnyaxe/sk_3': 0.8125,
  'bunnyaxe/stagger': 0.974,
  'bunnyaxe/strike': 1.0492,
  'bunnyaxe/win': 1.6271,
  'bunnyaxe/windup': 1.28,
  'card/m01_1': 1.3813,
  'card/m01_2': 1.3617,
  'card/m01_3': 1.3913,
  'card/m01_4': 1.3714,
  'card/m02_1': 1.2715,
  'card/m02_2': 1.2468,
  'card/m02_3': 1.28,
  'card/m02_4': 1.2715,
  'card/m03_1': 1.2229,
  'card/m03_2': 1.2,
  'card/m03_3': 1.2308,
  'card/m03_4': 1.2229,
  'card/m04_1': 1.2,
  'card/m04_2': 1.1707,
  'card/m04_3': 1.2075,
  'card/m04_4': 1.2,
  'card/m05_1': 1.2152,
  'card/m05_2': 1.1925,
  'card/m05_3': 1.2308,
  'card/m05_4': 1.2152,
  'card/m06_1': 1.2229,
  'card/m06_2': 1.2,
  'card/m06_3': 1.2308,
  'card/m06_4': 1.2152,
  'card/m07_1': 1.2229,
  'card/m07_2': 1.2,
  'card/m07_3': 1.2308,
  'card/m07_4': 1.2152,
  'card/m08_1': 1.2308,
  'card/m08_2': 1.2075,
  'card/m08_3': 1.2308,
  'card/m08_4': 1.2152,
  'card/m09_1': 1.2549,
  'card/m09_2': 1.2387,
  'card/m09_3': 1.2387,
  'card/m09_4': 1.2468,
  'card/m10_1': 1.28,
  'card/m10_2': 1.2715,
  'card/m10_3': 1.2715,
  'card/m10_4': 1.28,
  'card_back/checker': 1.7523,
  'card_back/diamond': 1.7685,
  'card_back/frames': 1.7523,
  'card_back/frames2': 1.7685,
  'card_back/lattice': 1.8019,
  'coin/copper': 1.0,
  'coin/gold': 0.9531,
  'coin/silver': 0.9792,
  'cr_bat/attack': 0.4271,
  'cr_bat/down': 0.3802,
  'cr_bat/idle': 0.4427,
  'cr_bat/windup': 0.7188,
  'cr_boar/attack': 0.7396,
  'cr_boar/down': 0.5417,
  'cr_boar/idle': 0.7135,
  'cr_boar/windup': 0.75,
  'cr_golem/attack': 0.8958,
  'cr_golem/down': 0.7188,
  'cr_golem/idle': 1.0323,
  'cr_golem/windup': 0.8177,
  'cr_mantis/attack': 0.9167,
  'cr_mantis/down': 0.6875,
  'cr_mantis/idle': 1.0159,
  'cr_mantis/windup': 0.9583,
  'cr_ogre/attack': 1.0608,
  'cr_ogre/down': 0.599,
  'cr_ogre/idle': 1.5,
  'cr_ogre/windup': 1.1925,
  'cr_skeleton/attack': 0.901,
  'cr_skeleton/down': 0.4635,
  'cr_skeleton/idle': 1.4118,
  'cr_skeleton/windup': 1.0492,
  'cr_slime/attack': 0.4531,
  'cr_slime/down': 0.4583,
  'cr_slime/idle': 0.8177,
  'cr_slime/windup': 0.5365,
  'cr_tentacle/attack': 0.4323,
  'cr_tentacle/down': 0.224,
  'cr_tentacle/idle': 0.7135,
  'cr_tentacle/windup': 0.6406,
  'cr_toad/attack': 0.5052,
  'cr_toad/down': 0.5052,
  'cr_toad/idle': 0.7292,
  'cr_toad/windup': 0.6458,
  'cr_wolf/attack': 0.6146,
  'cr_wolf/down': 0.401,
  'cr_wolf/idle': 0.849,
  'cr_wolf/windup': 0.6146,
  'creature/bat': 0.6354,
  'creature/boar': 0.8698,
  'creature/golem': 0.9583,
  'creature/mantis': 1.1228,
  'creature/ogre': 1.4656,
  'creature/skeleton': 1.3521,
  'creature/slime': 0.8438,
  'creature/tentacle': 1.0492,
  'creature/toad': 0.8854,
  'creature/wolf': 0.724,
  'crowd/cheer': 0.7448,
  'crowd/jeer': 0.7188,
  'crowd/neutral': 0.7031,
  'crowd/react_cheer': 0.7744,
  'crowd/react_jeer': 0.9375,
  'crowd/react_tension': 1.0,
  'duel/guard': 1.4766,
  'duel/hit': 1.6271,
  'duel/lose': 0.7969,
  'duel/recover': 1.4453,
  'duel/stagger': 1.4237,
  'duel/strike': 0.8958,
  'duel/win': 1.901,
  'duel/windup': 1.4436,
  'elf/portrait': 1.0323,
  'elf/stand': 1.4656,
  'elfarcher/cut_1': 1.3741,
  'elfarcher/cut_2': 1.1105,
  'elfarcher/cut_3': 1.0269,
  'elfarcher/guard': 1.5484,
  'elfarcher/hit': 1.2468,
  'elfarcher/lose': 1.1034,
  'elfarcher/recover': 1.4545,
  'elfarcher/sk_1': 1.2075,
  'elfarcher/sk_2': 1.0,
  'elfarcher/sk_3': 1.0323,
  'elfarcher/stagger': 1.1636,
  'elfarcher/strike': 1.1429,
  'elfarcher/win': 1.6,
  'elfarcher/windup': 1.4328,
  'elfarcher_shot/shot_1': 0.125,
  'elfarcher_shot/shot_2': 0.1198,
  'elfarcher_shot/shot_3': 0.1354,
  'eq_axe/t1': 1.0813,
  'eq_axe/t10': 1.1163,
  'eq_axe/t11': 0.8542,
  'eq_axe/t2': 1.0,
  'eq_axe/t3': 1.0109,
  'eq_axe/t4': 1.0109,
  'eq_axe/t5': 1.0378,
  'eq_axe/t6': 1.1852,
  'eq_axe/t7': 1.2075,
  'eq_axe/t8': 1.2,
  'eq_axe/t9': 1.2,
  'eq_belt/t1': 0.4558,
  'eq_belt/t10': 0.8836,
  'eq_belt/t11': 0.5,
  'eq_belt/t2': 0.2692,
  'eq_belt/t3': 0.4497,
  'eq_belt/t4': 0.3041,
  'eq_belt/t5': 0.3408,
  'eq_belt/t6': 0.4,
  'eq_belt/t7': 0.3191,
  'eq_belt/t8': 0.3404,
  'eq_belt/t9': 0.4894,
  'eq_blade/t1': 1.561,
  'eq_blade/t10': 1.2973,
  'eq_blade/t11': 0.8877,
  'eq_blade/t2': 1.4884,
  'eq_blade/t3': 1.3714,
  'eq_blade/t4': 1.2886,
  'eq_blade/t5': 1.2715,
  'eq_blade/t6': 1.5,
  'eq_blade/t7': 1.5,
  'eq_blade/t8': 1.5,
  'eq_blade/t9': 1.3617,
  'eq_boot/t1': 1.0137,
  'eq_boot/t10': 1.0114,
  'eq_boot/t11': 0.9419,
  'eq_boot/t2': 0.981,
  'eq_boot/t3': 0.9938,
  'eq_boot/t4': 1.0247,
  'eq_boot/t5': 1.0427,
  'eq_boot/t6': 1.0566,
  'eq_boot/t7': 0.994,
  'eq_boot/t8': 1.0769,
  'eq_boot/t9': 1.0595,
  'eq_bow/t1': 3.5682,
  'eq_bow/t10': 0.9375,
  'eq_bow/t11': 3.0,
  'eq_bow/t2': 4.3846,
  'eq_bow/t3': 3.0893,
  'eq_bow/t4': 3.8085,
  'eq_bow/t5': 3.7647,
  'eq_bow/t6': 3.6226,
  'eq_bow/t7': 1.8614,
  'eq_bow/t8': 3.8125,
  'eq_bow/t9': 1.5484,
  'eq_chest/t1': 1.3577,
  'eq_chest/t10': 1.3617,
  'eq_chest/t11': 1.2069,
  'eq_chest/t2': 1.3333,
  'eq_chest/t3': 1.2847,
  'eq_chest/t4': 1.4656,
  'eq_chest/t5': 1.4884,
  'eq_chest/t6': 1.4545,
  'eq_chest/t7': 1.1707,
  'eq_chest/t8': 1.4656,
  'eq_chest/t9': 1.3061,
  'eq_crossbow/t1': 0.8827,
  'eq_crossbow/t10': 0.8956,
  'eq_crossbow/t11': 0.7865,
  'eq_crossbow/t2': 0.8614,
  'eq_crossbow/t3': 0.8488,
  'eq_crossbow/t4': 0.8382,
  'eq_crossbow/t5': 0.8297,
  'eq_crossbow/t6': 0.8636,
  'eq_crossbow/t7': 0.7809,
  'eq_crossbow/t8': 0.8125,
  'eq_crossbow/t9': 0.8652,
  'eq_ear/t1': 2.1724,
  'eq_ear/t10': 1.5,
  'eq_ear/t11': 2.9649,
  'eq_ear/t2': 0.68,
  'eq_ear/t3': 0.8865,
  'eq_ear/t4': 2.8033,
  'eq_ear/t5': 1.6875,
  'eq_ear/t6': 2.2,
  'eq_ear/t7': 2.806,
  'eq_ear/t8': 2.8923,
  'eq_ear/t9': 2.4,
  'eq_fan/t1': 0.7656,
  'eq_fan/t10': 1.0,
  'eq_fan/t11': 0.6302,
  'eq_fan/t2': 0.6549,
  'eq_fan/t3': 0.6353,
  'eq_fan/t4': 0.6087,
  'eq_fan/t5': 0.6406,
  'eq_fan/t6': 0.6593,
  'eq_fan/t7': 0.6354,
  'eq_fan/t8': 0.6387,
  'eq_fan/t9': 0.7031,
  'eq_glove/t1': 2.0645,
  'eq_glove/t10': 2.087,
  'eq_glove/t11': 1.6216,
  'eq_glove/t2': 2.0,
  'eq_glove/t3': 1.92,
  'eq_glove/t4': 2.0,
  'eq_glove/t5': 1.9592,
  'eq_glove/t6': 1.9794,
  'eq_glove/t7': 2.1573,
  'eq_glove/t8': 2.0645,
  'eq_glove/t9': 2.0211,
  'eq_greaves/t1': 1.1349,
  'eq_greaves/t10': 0.875,
  'eq_greaves/t11': 1.2585,
  'eq_greaves/t2': 1.1694,
  'eq_greaves/t3': 1.155,
  'eq_greaves/t4': 1.252,
  'eq_greaves/t5': 0.883,
  'eq_greaves/t6': 1.2632,
  'eq_greaves/t7': 0.8281,
  'eq_greaves/t8': 1.218,
  'eq_greaves/t9': 1.1736,
  'eq_hammer/t1': 1.1166,
  'eq_hammer/t10': 1.6754,
  'eq_hammer/t11': 0.9096,
  'eq_hammer/t2': 1.027,
  'eq_hammer/t3': 1.0183,
  'eq_hammer/t4': 1.0312,
  'eq_hammer/t5': 1.0121,
  'eq_hammer/t6': 1.7944,
  'eq_hammer/t7': 1.8462,
  'eq_hammer/t8': 1.8725,
  'eq_hammer/t9': 1.7615,
  'eq_helm/t1': 1.1293,
  'eq_helm/t10': 1.2549,
  'eq_helm/t11': 1.4048,
  'eq_helm/t2': 1.1156,
  'eq_helm/t3': 1.2468,
  'eq_helm/t4': 1.3333,
  'eq_helm/t5': 1.2387,
  'eq_helm/t6': 1.2308,
  'eq_helm/t7': 1.3521,
  'eq_helm/t8': 1.2973,
  'eq_helm/t9': 1.3061,
  'eq_mace/t1': 1.3427,
  'eq_mace/t10': 1.3813,
  'eq_mace/t11': 0.9045,
  'eq_mace/t2': 1.3333,
  'eq_mace/t3': 1.28,
  'eq_mace/t4': 1.3617,
  'eq_mace/t5': 1.3617,
  'eq_mace/t6': 1.4015,
  'eq_mace/t7': 1.4118,
  'eq_mace/t8': 1.3521,
  'eq_mace/t9': 1.3913,
  'eq_neck/t1': 1.7449,
  'eq_neck/t10': 1.8113,
  'eq_neck/t11': 1.625,
  'eq_neck/t2': 1.732,
  'eq_neck/t3': 1.3534,
  'eq_neck/t4': 1.6923,
  'eq_neck/t5': 1.6283,
  'eq_neck/t6': 1.2194,
  'eq_neck/t7': 1.5447,
  'eq_neck/t8': 1.1852,
  'eq_neck/t9': 1.6271,
  'eq_ring/t1': 1.186,
  'eq_ring/t10': 1.3309,
  'eq_ring/t11': 1.1933,
  'eq_ring/t2': 1.1667,
  'eq_ring/t3': 1.2063,
  'eq_ring/t4': 1.1825,
  'eq_ring/t5': 1.1603,
  'eq_ring/t6': 1.1866,
  'eq_ring/t7': 1.0851,
  'eq_ring/t8': 1.25,
  'eq_ring/t9': 1.209,
  'eq_rod/t1': 4.8,
  'eq_rod/t10': 3.6923,
  'eq_rod/t11': 0.9048,
  'eq_rod/t2': 6.8571,
  'eq_rod/t3': 5.6471,
  'eq_rod/t4': 6.6207,
  'eq_rod/t5': 5.0263,
  'eq_rod/t6': 4.4651,
  'eq_rod/t7': 5.8182,
  'eq_rod/t8': 4.0851,
  'eq_rod/t9': 4.0851,
  'eq_spear/t1': 1.2886,
  'eq_spear/t10': 1.4118,
  'eq_spear/t11': 0.8177,
  'eq_spear/t2': 1.3714,
  'eq_spear/t3': 1.3427,
  'eq_spear/t4': 1.3714,
  'eq_spear/t5': 1.3617,
  'eq_spear/t6': 1.4222,
  'eq_spear/t7': 1.4118,
  'eq_spear/t8': 1.4118,
  'eq_spear/t9': 1.4222,
  'eq_staff/t1': 1.2279,
  'eq_staff/t10': 1.3521,
  'eq_staff/t11': 0.8385,
  'eq_staff/t2': 1.1852,
  'eq_staff/t3': 1.1707,
  'eq_staff/t4': 1.2,
  'eq_staff/t5': 1.2549,
  'eq_staff/t6': 1.2715,
  'eq_staff/t7': 1.2715,
  'eq_staff/t8': 1.3241,
  'eq_staff/t9': 1.3061,
  'eq_sword/t1': 1.1408,
  'eq_sword/t10': 1.2152,
  'eq_sword/t11': 0.849,
  'eq_sword/t2': 1.1871,
  'eq_sword/t3': 1.1163,
  'eq_sword/t4': 1.1034,
  'eq_sword/t5': 1.0787,
  'eq_sword/t6': 1.28,
  'eq_sword/t7': 1.3427,
  'eq_sword/t8': 1.3714,
  'eq_sword/t9': 1.3521,
  'event/attend': 0.6562,
  'event/bonus': 0.6302,
  'event/ended': 0.6458,
  'event/gift': 0.5938,
  'event/notice': 0.6562,
  'event/notice_alt': 0.6146,
  'event/season': 0.6458,
  'event/season_alt': 0.6771,
  'family/beast': 1.4242,
  'family/fish': 0.4525,
  'family/herb': 1.0336,
  'family/mushroom': 1.0,
  'family/ore': 0.9078,
  'food/booze': 1.4328,
  'food/bread': 0.8125,
  'food/stew': 1.0213,
  'food/water': 1.3023,
  'fx/burst_1': 1.0,
  'fx/burst_2': 0.9184,
  'fx/burst_3': 0.8686,
  'fx/burst_4': 0.8276,
  'fx/burst_5': 0.9008,
  'fx/glow_1': 0.5536,
  'fx/glow_2': 0.6977,
  'fx/glow_3': 0.7321,
  'fx/glow_4': 0.621,
  'fx/glow_5': 0.6983,
  'fx/shatter_1': 0.5766,
  'fx/shatter_2': 0.5766,
  'fx/shatter_3': 0.8346,
  'fx/shatter_4': 0.7589,
  'fx/shatter_5': 0.7559,
  'fx/smoke_1': 0.9825,
  'fx/smoke_2': 0.9419,
  'fx/smoke_3': 0.9333,
  'fx/smoke_4': 0.9439,
  'fx/smoke_5': 1.0,
  'fx_rune/1': 0.994,
  'fx_rune/2': 1.0,
  'fx_rune/3': 1.0,
  'fx_rune/4': 0.901,
  'fx_rune/5': 0.9462,
  'gear/belt': 0.5657,
  'gear/boot': 1.1899,
  'gear/chest': 1.3333,
  'gear/ear': 2.2326,
  'gear/glove': 1.8286,
  'gear/greaves': 1.1779,
  'gear/helm': 1.3813,
  'gear/neck': 1.2632,
  'gear/ring': 1.2533,
  'grade/g1': 0.9792,
  'grade/g2': 0.974,
  'grade/g3': 1.1228,
  'grade/g4': 1.0726,
  'grade/g5': 1.1707,
  'grade/g6': 0.9115,
  'grade/g7': 0.8438,
  'grade/g8': 0.9583,
  'grade/g9': 1.0,
  'guild/01': 1.12,
  'guild/02': 0.9651,
  'guild/03': 1.137,
  'guild/04': 1.137,
  'guild/05': 1.0784,
  'guild/06': 0.9649,
  'guild/07': 1.1301,
  'guild/08': 0.9706,
  'guild/09': 1.0253,
  'guild/10': 1.1844,
  'guild/11': 1.1844,
  'guild/12': 0.9167,
  'guild/13': 1.2891,
  'guild/14': 1.1,
  'guild/15': 0.9429,
  'guild_ui/banner': 1.2308,
  'guild_ui/chevron': 1.2424,
  'guild_ui/master': 1.3636,
  'guild_ui/member': 1.1053,
  'guild_ui/members': 0.7969,
  'guild_ui/rank1': 0.9219,
  'guild_ui/rank2': 0.9375,
  'guild_ui/rank3': 0.7656,
  'holo/body': 0.9583,
  'holo/body_x': 0.8281,
  'holo/bullet': 4.2083,
  'holo/head': 1.0213,
  'holo/head_x': 1.0,
  'holo/ship': 1.2414,
  'holo/tail': 0.9062,
  'holo/tail_x': 0.8854,
  'jackpot/01': 1.0,
  'jackpot/02': 1.0267,
  'jackpot/03': 1.0267,
  'jackpot/04': 1.0435,
  'jackpot/05': 1.0549,
  'job/bellows': 0.7656,
  'job/broom': 1.1497,
  'job/bucket': 1.2715,
  'job/cart': 0.9323,
  'job/flyer': 1.0,
  'job/hay': 1.3714,
  'job/ice': 1.0726,
  'job/shovel': 1.0787,
  'knightgirl/cut_1': 1.3061,
  'knightgirl/cut_2': 0.9791,
  'knightgirl/cut_3': 0.8802,
  'knightgirl/guard': 1.3241,
  'knightgirl/hit': 1.3061,
  'knightgirl/lose': 0.7552,
  'knightgirl/recover': 1.2,
  'knightgirl/sk_1': 1.1779,
  'knightgirl/sk_2': 0.9167,
  'knightgirl/sk_3': 1.0105,
  'knightgirl/stagger': 0.9792,
  'knightgirl/strike': 0.8906,
  'knightgirl/win': 1.4769,
  'knightgirl/windup': 1.1497,
  'knightgirl_wave/wave_1': 1.8113,
  'knightgirl_wave/wave_2': 1.2468,
  'knightgirl_wave/wave_3': 1.1779,
  'lottery/rank1': 1.0,
  'lottery/rank2': 0.9944,
  'lottery/rank3': 1.0057,
  'lottery/rank4': 0.9944,
  'lottery/rank5': 1.0,
  'lottery/ticket_clover': 0.6667,
  'lottery/ticket_plain': 0.6667,
  'lottery/ticket_torn': 0.6705,
  'lottery/ticket_torn2': 0.6821,
  'maid/happy': 2.1333,
  'maid/portrait': 2.1818,
  'maid/shy': 2.1573,
  'maid/stand': 2.4615,
  'map/forest': 0.8177,
  'map/rift': 1.0,
  'map/ruin': 0.7917,
  'map/sea': 0.7604,
  'map/snow': 0.7917,
  'map/town': 0.7969,
  'map/wild': 0.8073,
  'map_pin/banner': 1.4436,
  'map_pin/compass': 1.0608,
  'map_pin/here': 1.1228,
  'map_pin/locked': 1.2715,
  'map_pin/road_node': 1.026,
  'map_pin/signpost': 1.0847,
  'map_pin/unvisited': 1.3061,
  'map_pin/visited': 1.2715,
  'material/bone': 0.9792,
  'material/skin': 1.0378,
  'material/tooth': 1.25,
  'mines/bomb': 0.8333,
  'mines/closed': 0.8438,
  'mines/flag': 0.9844,
  'mines/open': 0.8646,
  'nun/cut_1': 1.6238,
  'nun/cut_2': 0.948,
  'nun/cut_3': 1.3782,
  'nun/guard': 2.2597,
  'nun/hit': 1.4194,
  'nun/lose': 1.4455,
  'nun/recover': 1.5446,
  'nun/sk_1': 1.2845,
  'nun/sk_2': 1.092,
  'nun/sk_3': 1.0833,
  'nun/stagger': 0.9085,
  'nun/strike': 1.1457,
  'nun/win': 2.5429,
  'nun/windup': 1.376,
  'nun_wave/wave_1': 1.4615,
  'nun_wave/wave_2': 1.7143,
  'nun_wave/wave_3': 4.2414,
  'pl_attack/cast_1': 1.0294,
  'pl_attack/cast_2': 0.4062,
  'pl_attack/cast_3': 1.4688,
  'pl_attack/shoot_1': 1.0879,
  'pl_attack/shoot_2': 0.4792,
  'pl_attack/shoot_3': 1.1882,
  'pl_attack/slash_1': 1.3889,
  'pl_attack/slash_2': 0.887,
  'pl_attack/slash_3': 0.7478,
  'pl_attack/smash_1': 1.2683,
  'pl_attack/smash_2': 0.6533,
  'pl_attack/smash_3': 0.8586,
  'pl_attack/thrust_1': 0.5833,
  'pl_attack/thrust_2': 0.3646,
  'pl_attack/thrust_3': 0.5769,
  'player/breathe': 1.4545,
  'player/defeated': 1.0844,
  'player/idle': 2.1099,
  'player/victory': 1.0726,
  'potion/high': 0.9202,
  'potion/low': 1.4747,
  'potion/mid': 1.7826,
  'raid_boss/d01': 1.0169,
  'raid_boss/d02': 1.3094,
  'raid_boss/d03': 0.8202,
  'raid_boss/d04': 1.5776,
  'raid_boss/d05': 1.0492,
  'raid_boss/d06': 1.0281,
  'raid_boss/d07': 0.8415,
  'raid_boss/d08': 0.8324,
  'raid_boss/d09': 1.011,
  'raid_boss/d10': 1.0492,
  'raid_boss/s01': 1.2152,
  'raid_boss/s02': 0.9479,
  'raid_boss/s03': 1.2468,
  'raid_boss/w01': 1.0549,
  'raid_boss/w02': 1.0378,
  'raid_boss/w03': 1.2973,
  'role_icon/role_melee': 3.0,
  'role_icon/role_ranged': 1.1429,
  'role_icon/role_support': 0.9892,
  'role_icon/role_tank': 1.0159,
  'sb_acid/attack': 0.9062,
  'sb_acid/down': 1.0,
  'sb_acid/idle': 0.8021,
  'sb_bone/attack': 0.9479,
  'sb_bone/down': 0.9688,
  'sb_bone/idle': 1.0492,
  'sb_grass/attack': 0.8168,
  'sb_grass/down': 0.7708,
  'sb_grass/idle': 0.9791,
  'sb_king/attack': 0.8229,
  'sb_king/down': 0.9005,
  'sb_king/idle': 0.9688,
  'sb_mud/attack': 0.8958,
  'sb_mud/down': 0.8325,
  'sb_mud/idle': 0.9844,
  'sb_spore/attack': 0.8594,
  'sb_spore/down': 1.0726,
  'sb_spore/idle': 1.3521,
  'sb_stone/attack': 0.7396,
  'sb_stone/down': 0.8021,
  'sb_stone/idle': 0.8646,
  'sb_thorn/attack': 0.9062,
  'sb_thorn/down': 0.9688,
  'sb_thorn/idle': 0.9896,
  'sb_twin/attack': 0.7865,
  'sb_twin/down': 0.7865,
  'sb_twin/idle': 0.8125,
  'scroll/guarantee': 1.6552,
  'scroll/guard_destroy100': 0.9531,
  'scroll/guard_destroy50': 1.0787,
  'scroll/guard_down': 1.0971,
  'scroll/succ_high': 1.1034,
  'scroll/succ_low': 1.1098,
  'scroll/succ_mid': 1.1228,
  'sg_acid/attack': 0.849,
  'sg_acid/down': 1.0323,
  'sg_acid/idle': 1.0608,
  'sg_bone/attack': 1.5917,
  'sg_bone/down': 1.2973,
  'sg_bone/idle': 1.8113,
  'sg_grass/attack': 0.651,
  'sg_grass/down': 0.6615,
  'sg_grass/idle': 0.9167,
  'sg_mud/attack': 0.9792,
  'sg_mud/down': 0.6771,
  'sg_mud/idle': 1.3913,
  'sg_spore/attack': 1.0909,
  'sg_spore/down': 0.8542,
  'sg_spore/idle': 1.0549,
  'sg_stone/attack': 0.8542,
  'sg_stone/down': 0.9115,
  'sg_stone/idle': 0.9948,
  'sg_thorn/attack': 0.651,
  'sg_thorn/down': 0.8229,
  'sg_thorn/idle': 0.9271,
  'sg_twin/attack': 0.6406,
  'sg_twin/down': 0.6771,
  'sg_twin/idle': 0.6458,
  'single_icon/01': 1.0437,
  'single_icon_alt/01': 1.0,
  'single_splash/01': 1.1566,
  'skill_icon/sk_heal': 0.7135,
  'skill_icon/sk_leap': 0.974,
  'skill_icon/sk_rain': 0.9896,
  'skill_icon/sk_wave': 0.8438,
  'sl_boss/attack': 0.9427,
  'sl_boss/down': 0.733,
  'sl_boss/idle': 0.9843,
  'sl_melee/attack': 0.5885,
  'sl_melee/down': 0.5573,
  'sl_melee/idle': 0.6667,
  'sl_ranged/attack': 0.9896,
  'sl_ranged/down': 0.8854,
  'sl_ranged/idle': 1.5118,
  'slot/_bracer': 1.1016,
  'slot/_ear2': 1.8824,
  'slot/belt': 0.4588,
  'slot/boot': 1.1429,
  'slot/chest': 0.9433,
  'slot/ear': 1.9692,
  'slot/glove': 1.6744,
  'slot/greaves': 0.9396,
  'slot/helm': 1.0667,
  'slot/neck': 1.2321,
  'slot/ring': 1.2157,
  'slot/sword': 1.0,
  'smith/portrait': 0.9323,
  'smith/stand': 1.3427,
  'sp_beast/blackbear': 0.6927,
  'sp_beast/boar': 0.6865,
  'sp_beast/fieldrat': 0.5455,
  'sp_beast/greywolf': 0.6522,
  'sp_beast/hare': 1.0602,
  'sp_beast/hornlessdeer': 1.1143,
  'sp_beast/icefox': 0.8249,
  'sp_beast/oneeyedowl': 1.3936,
  'sp_beast/onehornogre': 1.1716,
  'sp_beast/shadowpanther': 0.5138,
  'sp_beast/spinytoad': 0.7329,
  'sp_beast/steelmantis': 0.9623,
  'sp_fish/abysseel': 0.8281,
  'sp_fish/centuryturtle': 0.6406,
  'sp_fish/dragonsturgeon': 0.3802,
  'sp_fish/icetrout': 0.4792,
  'sp_fish/ironcarp': 0.6198,
  'sp_fish/lampangler': 0.6979,
  'sp_fish/minnow': 0.3958,
  'sp_fish/moonray': 0.8958,
  'sp_fish/mudcarp': 0.599,
  'sp_fish/riverpike': 0.3073,
  'sp_fish/silverscale': 0.5677,
  'sp_fish/spiritwhale': 0.7604,
  'sp_fish/whirltuna': 0.5833,
  'sp_fish/whiskercat': 0.526,
  'sp_herb/bandagemoss': 0.8438,
  'sp_herb/bitterleaf': 1.4884,
  'sp_herb/dewgrass': 1.0378,
  'sp_herb/dragonblood': 1.4436,
  'sp_herb/frostlily': 1.0378,
  'sp_herb/moonflower': 1.1925,
  'sp_herb/silverleaf': 1.2715,
  'sp_herb/spiritherb': 1.0726,
  'sp_mushroom/abyssspore': 1.16,
  'sp_mushroom/dirtcap': 1.1646,
  'sp_mushroom/dreamcap': 1.3,
  'sp_mushroom/lampcap': 1.2609,
  'sp_mushroom/moldcap': 1.0531,
  'sp_mushroom/panaceacap': 1.0526,
  'sp_mushroom/poisonbrolly': 1.4712,
  'sp_mushroom/spiritcap': 1.1128,
  'sp_ore/copperore': 0.901,
  'sp_ore/goldore': 0.8594,
  'sp_ore/ironore': 0.954,
  'sp_ore/mithrilbit': 0.75,
  'sp_ore/orichalcum': 0.8698,
  'sp_ore/pebble': 0.9713,
  'sp_ore/quartz': 1.1299,
  'sp_ore/silverore': 0.9219,
  'stone/high_crack': 1.0506,
  'stone/high_glow': 0.8438,
  'stone/high_idle': 1.1608,
  'stone/low_crack': 0.95,
  'stone/low_glow': 1.0741,
  'stone/low_idle': 1.2771,
  'stone/mid_crack': 0.9605,
  'stone/mid_glow': 0.9787,
  'stone/mid_idle': 1.1311,
  'synergy/crown': 1.0909,
  'synergy/leaf': 1.2468,
  'synergy/ring1': 1.0213,
  'synergy/ring2': 1.0213,
  'synergy/ring3': 1.0267,
  'synergy/rock': 0.8958,
  'synergy/rune': 1.5738,
  'synergy/wind': 0.9688,
  'tab/collection': 0.7595,
  'tab/etc': 0.7368,
  'tab/home': 1.305,
  'tab/money': 0.9195,
  'tab/town': 0.5529,
  'tierframe/_alt10': 0.8438,
  'tierframe/_alt4': 1.0195,
  'tierframe/_alt8': 1.0,
  'tierframe/t1': 1.0201,
  'tierframe/t10': 0.9655,
  'tierframe/t11': 0.9655,
  'tierframe/t2': 0.9441,
  'tierframe/t3': 0.9337,
  'tierframe/t4': 0.963,
  'tierframe/t5': 1.0136,
  'tierframe/t6': 0.9128,
  'tierframe/t7': 0.9027,
  'tierframe/t8': 0.9598,
  'tierframe/t9': 0.9884,
  'title/abyss_diver': 1.0,
  'title/alchemist': 1.0105,
  'title/all_in': 1.0,
  'title/angler': 1.0549,
  'title/artisan_path': 1.0052,
  'title/bankrupt_king': 1.0,
  'title/bernstein_slayer': 1.0,
  'title/coin_believer': 1.0608,
  'title/curator': 1.0052,
  'title/curse13': 1.0052,
  'title/day_trader': 1.0,
  'title/defaulter': 1.0052,
  'title/first_artisan': 1.1925,
  'title/first_hundred': 0.8906,
  'title/first_player': 1.0052,
  'title/first_sss': 0.9948,
  'title/first_summit': 1.0052,
  'title/first_thousand': 1.1361,
  'title/gather_king': 0.9948,
  'title/gladiator': 1.0052,
  'title/guild_founder': 1.2229,
  'title/gwang38': 1.0052,
  'title/hunter': 0.9948,
  'title/iron_wallet': 0.974,
  'title/lucky_hand': 1.3813,
  'title/night_owl': 1.0378,
  'title/polymath': 1.0,
  'title/rune_master': 0.9479,
  'title/rune_smith': 1.0105,
  'title/set_keeper': 1.0105,
  'title/tower_conqueror': 1.0,
  'title/veteran': 1.0052,
  'title/weapon_collector': 1.0052,
  'tool/fish': 0.9693,
  'tool/fish_A': 1.0,
  'tool/fish_B': 1.0,
  'tool/fish_C': 1.0213,
  'tool/fish_D': 1.0105,
  'tool/fish_E': 1.0323,
  'tool/fish_F': 1.0105,
  'tool/fish_S': 1.0323,
  'tool/gather': 0.8492,
  'tool/gather_A': 1.1034,
  'tool/gather_B': 1.1228,
  'tool/gather_C': 1.1163,
  'tool/gather_D': 1.1098,
  'tool/gather_E': 1.1707,
  'tool/gather_F': 1.1429,
  'tool/gather_S': 1.0378,
  'tool/hunt_A': 1.0323,
  'tool/hunt_B': 1.0971,
  'tool/hunt_C': 1.0159,
  'tool/hunt_D': 1.0105,
  'tool/hunt_E': 1.0378,
  'tool/hunt_F': 1.0213,
  'tool/hunt_S': 0.9635,
  'tutorial/check': 1.0069,
  'tutorial/drag': 1.1164,
  'tutorial/hint': 1.7447,
  'tutorial/point_down': 1.1833,
  'tutorial/point_left': 0.8571,
  'tutorial/point_right': 0.8521,
  'tutorial/point_up': 1.2,
  'tutorial/skip': 0.8493,
  'tutorial/tap': 1.0377,
  'tutorial/warn': 1.0946,
  'weapon/axe': 1.0105,
  'weapon/blade': 1.0847,
  'weapon/bow': 1.0159,
  'weapon/crossbow': 1.0159,
  'weapon/fan': 0.6719,
  'weapon/hammer': 1.0267,
  'weapon/mace': 1.0213,
  'weapon/rod': 1.0159,
  'weapon/spear': 1.0159,
  'weapon/staff': 1.0323,
  'weapon/sword': 1.0213,
};

/**
 * 정사각 상자 안에서 그림 **바닥**이 상자 바닥에서 얼마나 떠 있나 (0~0.5).
 *
 * 세로가 더 길면 0 이다 — 높이를 꽉 채우므로 뜰 자리가 없다.
 * 모르는 그림도 0 으로 둔다. 틀리면 그림자가 조금 낮게 깔릴 뿐이다.
 */
export function spriteGap(set: string, key: string): number {
  const r = SPRITE_RATIO[`${set}/${key}`];
  if (!r || r >= 1) return 0;
  return (1 - r) / 2;
}
